function curatedEntries() {
  const entries = [];

  function add(term, definition, category, tags = [], level = "intermediate", example) {
    entries.push({ term, definition, category, tags, level, example });
  }

  const fundamentals = [
    ["Variable", "Named storage location holding a value that can change during execution.", "beginner"],
    ["Constant", "Binding whose value must not change after initialization.", "beginner"],
    ["Literal", "Value written directly in source code (42, \"hello\", true).", "beginner"],
    ["Expression", "Code fragment that evaluates to a value.", "beginner"],
    ["Statement", "Complete unit of execution — assignment, if, return.", "beginner"],
    ["Block", "Group of statements enclosed in braces or indentation.", "beginner"],
    ["Scope", "Region of code where a variable name is visible.", "intermediate"],
    ["Lexical Scope", "Scope determined by source code nesting (static scope).", "intermediate"],
    ["Closure", "Function retaining access to variables from enclosing scope.", "intermediate"],
    ["Hoisting", "JavaScript behavior moving declarations before execution (var/function).", "intermediate"],
    ["Recursion", "Function calling itself with smaller subproblem.", "intermediate"],
    ["Iteration", "Repeating using loops instead of recursion.", "beginner"],
    ["Mutability", "Whether data can be changed after creation.", "intermediate"],
    ["Immutability", "Data cannot change — new copies instead of in-place edits.", "intermediate"],
    ["Side Effect", "Change observable outside function (I/O, global state).", "intermediate"],
    ["Pure Function", "Same inputs always produce same output with no side effects.", "intermediate"],
    ["Referential Transparency", "Expression can be replaced by its value without changing behavior.", "advanced"],
    ["Idempotent", "Operation safe to repeat — same result after first application.", "intermediate"],
    ["Deterministic", "Same input always yields same output.", "intermediate"],
    ["Nondeterministic", "Output may vary (random, concurrency, time).", "intermediate"],
    ["Concurrency", "Multiple tasks making progress — not necessarily parallel.", "advanced"],
    ["Parallelism", "Tasks literally run at same time on multiple cores.", "advanced"],
    ["Race Condition", "Outcome depends on unpredictable thread scheduling order.", "advanced"],
    ["Deadlock", "Threads blocked forever waiting for each other's locks.", "advanced"],
    ["Livelock", "Threads keep changing state but make no progress.", "advanced"],
    ["Mutex", "Mutual exclusion lock allowing one thread in critical section.", "advanced"],
    ["Semaphore", "Signaling mechanism limiting concurrent access count.", "advanced"],
    ["Monitor", "Synchronization construct with lock and condition variables.", "advanced"],
    ["Thread", "Lightweight unit of execution within a process.", "intermediate"],
    ["Process", "OS-managed program instance with own memory space.", "intermediate"],
    ["Coroutine", "Cooperative lightweight concurrency yielding control explicitly.", "advanced"],
    ["Green Thread", "User-space scheduled threads mapped to fewer OS threads.", "advanced"],
    ["Pointer", "Value holding memory address of another value.", "intermediate"],
    ["Reference", "Alias to existing object without copying (language-dependent).", "intermediate"],
    ["Dereference", "Access value at address pointed to by pointer.", "intermediate"],
    ["Null Pointer", "Pointer intentionally representing no object — dereference crashes.", "intermediate"],
    ["Segmentation Fault", "Accessing invalid memory — common C/C++ crash.", "intermediate"],
    ["Stack Overflow", "Exceeding call stack limit — often infinite recursion.", "intermediate"],
    ["Heap", "Memory region for dynamic allocation (malloc, new).", "intermediate"],
    ["Call Stack", "LIFO frames tracking active function calls and locals.", "intermediate"],
    ["Frame Pointer", "Register/pointer to current stack frame.", "advanced"],
    ["Register", "Fast CPU storage for operands and addresses.", "advanced"],
    ["Instruction Set", "CPU opcodes a processor can execute (x86, ARM).", "advanced"],
    ["Endianness", "Byte order in multi-byte values — little vs big endian.", "advanced"],
    ["Two's Complement", "Standard signed integer representation in binary.", "advanced"],
    ["Floating Point", "IEEE 754 approximate real number representation.", "intermediate"],
    ["NaN", "Not a Number — result of invalid float operations.", "intermediate"],
    ["Infinity", "Float value larger than finite representable range.", "intermediate"],
    ["Underflow", "Result too small to represent as normalized float.", "advanced"],
    ["Overflow", "Result exceeds maximum representable value.", "intermediate"],
    ["Type System", "Rules assigning types to expressions preventing invalid operations.", "intermediate"],
    ["Static Typing", "Types checked at compile time.", "intermediate"],
    ["Dynamic Typing", "Types checked at runtime.", "intermediate"],
    ["Strong Typing", "Few implicit conversions — types not silently coerced.", "intermediate"],
    ["Weak Typing", "Implicit conversions between unrelated types allowed.", "intermediate"],
    ["Type Inference", "Compiler deduces types without explicit annotations.", "intermediate"],
    ["Generics", "Parametric types/functions working across many types safely.", "advanced"],
    ["Polymorphism", "Same interface, different behavior per type.", "intermediate"],
    ["Inheritance", "Subclass acquires fields and methods from parent class.", "intermediate"],
    ["Encapsulation", "Hide internal state exposing controlled interface.", "intermediate"],
    ["Abstraction", "Hide complexity showing essential features only.", "intermediate"],
    ["Composition", "Build behavior by combining objects rather than inheriting.", "intermediate"],
    ["Interface", "Contract specifying methods without implementation.", "intermediate"],
    ["Abstract Class", "Class that cannot instantiate — may have abstract methods.", "intermediate"],
    ["Method Overloading", "Multiple methods same name different parameters.", "intermediate"],
    ["Method Overriding", "Subclass replaces parent method implementation.", "intermediate"],
    ["Virtual Method", "Dynamically dispatched based on runtime object type.", "advanced"],
    ["Multiple Inheritance", "Class inherits from more than one parent (C++, Python).", "advanced"],
    ["Mixin", "Class providing methods for multiple inheritance composition.", "advanced"],
    ["Trait", "Horizontal code reuse without full inheritance (Rust, PHP).", "advanced"],
    ["Delegate", "Object forwarding method calls to another object.", "intermediate"],
    ["Lambda Expression", "Anonymous function defined inline.", "intermediate"],
    ["Higher-Order Function", "Takes functions as args or returns function.", "intermediate"],
    ["First-Class Function", "Functions treated as values — assign, pass, return.", "intermediate"],
    ["Currying", "Transform multi-arg function into chain of single-arg functions.", "advanced"],
    ["Partial Application", "Fix some arguments producing function of remaining args.", "advanced"],
    ["Monad", "FP structure chaining computations (Optional, Result, IO).", "advanced"],
    ["Functor", "Type mappable over preserving structure (map).", "advanced"],
    ["Applicative Functor", "Apply function inside context to value inside context.", "advanced"],
    ["Immutable Data Structure", "Updates return new version sharing unchanged parts.", "advanced"],
    ["Persistent Data Structure", "Previous versions accessible after modification.", "advanced"],
    ["Copy-on-Write", "Duplicate data only when mutation would affect shared copy.", "advanced"],
    ["Serialization", "Convert object to storable/transmittable format.", "intermediate"],
    ["Deserialization", "Reconstruct object from serialized bytes.", "intermediate"],
    ["Marshalling", "Convert data for cross-process or network transfer.", "intermediate"],
    ["Endian Conversion", "Swap byte order when crossing CPU architectures.", "advanced"],
    ["Endianness Detection", "Runtime check of host byte order.", "advanced"],
    ["Bitwise AND", "Binary AND — 1 where both bits set.", "beginner"],
    ["Bitwise OR", "Binary OR — 1 where either bit set.", "beginner"],
    ["Bitwise XOR", "Binary XOR — 1 where bits differ.", "beginner"],
    ["Bit Shift Left", "Shift bits left multiplying by powers of two.", "beginner"],
    ["Bit Shift Right", "Shift bits right dividing (logical or arithmetic).", "beginner"],
    ["Bitmask", "Use integer bits as compact boolean flags.", "intermediate"],
    ["Compile Time", "When source is translated to executable before running.", "beginner"],
    ["Runtime", "When program is actually executing.", "beginner"],
    ["Interpreter", "Execute source line-by-line without prior full compilation.", "intermediate"],
    ["Transpiler", "Source-to-source compiler (TypeScript to JavaScript).", "intermediate"],
    ["Linker", "Combines object files and libraries into executable.", "advanced"],
    ["Loader", "OS loads executable into memory and starts execution.", "advanced"],
    ["Symbol Table", "Maps names to addresses during linking/debugging.", "advanced"],
    ["Debug Symbols", "Metadata mapping machine code to source lines.", "advanced"],
    ["Breakpoint", "Debugger pause when execution reaches line/address.", "beginner"],
    ["Watchpoint", "Debugger pause when memory location changes.", "intermediate"],
    ["Stack Trace", "List of call frames at error or breakpoint.", "beginner"],
    ["Core Dump", "Snapshot of process memory on crash for post-mortem.", "advanced"],
    ["Profiling", "Measure where program spends time or memory.", "intermediate"],
    ["Flame Graph", "Visualization of stack samples showing hot paths.", "advanced"],
    ["Benchmark", "Controlled performance measurement of code path.", "intermediate"],
    ["Microbenchmark", "Measure tiny code snippet — beware JIT/dead code elimination.", "advanced"],
    ["Regression Test", "Ensure previously fixed bug does not reappear.", "intermediate"],
    ["Smoke Test", "Quick sanity check that build basically works.", "intermediate"],
    ["Integration Test", "Verify multiple components work together.", "intermediate"],
    ["Unit Test", "Test isolated function or class in isolation.", "beginner"],
    ["End-to-End Test", "Automate full user flow through real UI.", "intermediate"],
    ["Mock Object", "Fake dependency with controlled behavior for tests.", "intermediate"],
    ["Stub", "Minimal fake returning canned responses.", "intermediate"],
    ["Spy", "Records how fake was called for assertions.", "intermediate"],
    ["Fixture", "Known test data setup reused across tests.", "intermediate"],
    ["Test Coverage", "Percentage of code executed by test suite.", "intermediate"],
    ["Code Review", "Peer examination of changes before merge.", "beginner"],
    ["Pull Request", "Proposed changes for review before merging to main branch.", "beginner"],
    ["Merge Conflict", "Git cannot auto-merge overlapping edits — manual resolution.", "intermediate"],
    ["Feature Branch", "Short-lived branch for one feature or fix.", "beginner"],
    ["Trunk-Based Development", "Small frequent commits directly to main with flags.", "intermediate"],
    ["Semantic Versioning", "MAJOR.MINOR.PATCH — breaking, feature, fix.", "intermediate"],
    ["Changelog", "Human-readable list of changes per release.", "beginner"],
    ["Deprecation", "Mark API obsolete with planned removal timeline.", "intermediate"],
    ["Backward Compatibility", "New version works with clients expecting old behavior.", "intermediate"],
    ["Breaking Change", "Change requiring clients to update integration.", "intermediate"],
    ["Technical Debt", "Shortcuts taken now costing maintenance later.", "intermediate"],
    ["Refactoring", "Improve structure without changing external behavior.", "intermediate"],
    ["Code Smell", "Surface sign of deeper design problem.", "intermediate"],
    ["Cyclomatic Complexity", "Metric counting independent paths through code.", "advanced"],
    ["Coupling", "Degree modules depend on each other's internals.", "intermediate"],
    ["Cohesion", "How closely related responsibilities within module are.", "intermediate"],
    ["Separation of Concerns", "Split system into distinct responsibilities.", "intermediate"],
    ["Single Responsibility Principle", "Class/module should have one reason to change.", "intermediate"],
    ["Open-Closed Principle", "Open for extension, closed for modification.", "intermediate"],
    ["Liskov Substitution Principle", "Subtypes must be substitutable for base types.", "advanced"],
    ["Interface Segregation Principle", "Clients shouldn't depend on unused interfaces.", "advanced"],
    ["Dependency Inversion Principle", "Depend on abstractions not concretions.", "advanced"],
  ];
  for (const [term, definition, level] of fundamentals) {
    add(term, definition, "fundamentals", ["fundamentals"], level);
  }

  const dbTerms = [
    ["Primary Key", "Column(s) uniquely identifying each row in table.", "beginner"],
    ["Foreign Key", "Column referencing primary key in another table.", "beginner"],
    ["Composite Key", "Primary key made of multiple columns together.", "intermediate"],
    ["Natural Key", "Business-meaningful identifier (email, ISBN).", "intermediate"],
    ["Surrogate Key", "System-generated ID with no business meaning (auto-increment).", "intermediate"],
    ["Normalization", "Organize tables reducing redundancy (1NF, 2NF, 3NF, BCNF).", "intermediate"],
    ["Denormalization", "Introduce redundancy intentionally for read performance.", "intermediate"],
    ["ACID Transaction", "Atomic consistent isolated durable database operation.", "intermediate"],
    ["Isolation Level", "How much concurrent transactions see each other's changes.", "advanced"],
    ["Read Uncommitted", "Lowest isolation — dirty reads possible.", "advanced"],
    ["Read Committed", "Only see committed data — no dirty reads.", "advanced"],
    ["Repeatable Read", "Same row reads consistent within transaction.", "advanced"],
    ["Serializable", "Strongest isolation — transactions appear sequential.", "advanced"],
    ["Dirty Read", "Reading uncommitted changes from another transaction.", "advanced"],
    ["Phantom Read", "New rows appear in repeated range query.", "advanced"],
    ["Write Skew", "Concurrent transactions read overlapping data and write inconsistently.", "advanced"],
    ["Optimistic Locking", "Detect conflict at commit using version column.", "advanced"],
    ["Pessimistic Locking", "Lock rows upfront preventing concurrent writes.", "advanced"],
    ["Deadlock Detection", "DB detects circular lock wait and aborts victim.", "advanced"],
    ["WAL", "Write-Ahead Log — changes logged before applying to pages.", "advanced"],
    ["Redo Log", "Record changes for crash recovery replay.", "advanced"],
    ["Undo Log", "Record old values for transaction rollback.", "advanced"],
    ["Checkpoint", "Flush dirty buffers marking recovery start point.", "advanced"],
    ["Vacuum", "PostgreSQL reclaim dead tuple space.", "advanced"],
    ["Autovacuum", "Automatic PostgreSQL vacuum background process.", "advanced"],
    ["Query Plan", "Database chosen steps to execute SQL (EXPLAIN).", "intermediate"],
    ["Index Scan", "Use index to find matching rows efficiently.", "intermediate"],
    ["Sequential Scan", "Read entire table — slow on large data.", "intermediate"],
    ["Covering Index", "Index includes all columns query needs — no table lookup.", "advanced"],
    ["Partial Index", "Index subset of rows matching condition.", "advanced"],
    ["Materialized View", "Stored query result refreshed periodically.", "advanced"],
    ["Sharding", "Split data across multiple database instances by key.", "advanced"],
    ["Replication", "Copy data to standby nodes for read scaling or failover.", "advanced"],
    ["Leader Election", "Choose one primary writer among replicas.", "advanced"],
    ["Split Brain", "Two nodes both think they are primary — data divergence.", "advanced"],
    ["Eventual Consistency", "Replicas converge over time without immediate sync.", "advanced"],
    ["Strong Consistency", "Read always returns latest committed write.", "advanced"],
    ["Quorum", "Minimum replicas agreeing before acknowledging write.", "advanced"],
    ["CAP Theorem", "Distributed system cannot have all three: consistency, availability, partition tolerance.", "advanced"],
    ["NoSQL", "Non-relational databases — document, key-value, column, graph.", "intermediate"],
    ["Document Database", "Store JSON-like documents (MongoDB, CouchDB).", "intermediate"],
    ["Key-Value Store", "Simple get/put by key (Redis, DynamoDB).", "intermediate"],
    ["Column Family", "Wide-column store (Cassandra, HBase).", "advanced"],
    ["Graph Database", "Nodes and edges native (Neo4j).", "advanced"],
    ["Time-Series Database", "Optimized for timestamped metrics (InfluxDB, TimescaleDB).", "advanced"],
    ["Vector Database", "Similarity search on embeddings (Pinecone, pgvector).", "advanced"],
    ["Connection Pool", "Reuse DB connections avoiding connect overhead.", "intermediate"],
    ["Prepared Statement", "SQL compiled once executed many times with parameters.", "intermediate"],
    ["SQL Injection Prevention", "Use parameterized queries never string concatenation.", "intermediate"],
    ["Migration", "Versioned schema change scripts applied in order.", "intermediate"],
    ["Seed Data", "Initial rows inserted after schema creation.", "beginner"],
    ["ER Diagram", "Entity-Relationship diagram modeling tables and relations.", "beginner"],
    ["Cardinality", "Relationship multiplicity — one-to-one, one-to-many, many-to-many.", "intermediate"],
    ["Junction Table", "Associates many-to-many relationship between entities.", "intermediate"],
    ["Soft Delete", "Mark row deleted with flag instead of physical DELETE.", "intermediate"],
    ["Hard Delete", "Physically remove row from table.", "beginner"],
    ["Audit Trail", "Log who changed what and when for compliance.", "intermediate"],
  ];
  for (const [term, definition, level] of dbTerms) {
    add(term, definition, "databases", ["database", "sql"], level);
  }

  const aiTerms = [
    ["Supervised Learning", "Train on labeled input-output pairs.", "intermediate"],
    ["Unsupervised Learning", "Find patterns in unlabeled data.", "intermediate"],
    ["Reinforcement Learning", "Agent learns by reward signal from environment.", "advanced"],
    ["Feature", "Individual measurable property of input data.", "intermediate"],
    ["Label", "Correct output value in supervised training.", "intermediate"],
    ["Training Set", "Data used to fit model parameters.", "intermediate"],
    ["Validation Set", "Data for tuning hyperparameters without touching test.", "intermediate"],
    ["Test Set", "Held-out data for final unbiased evaluation.", "intermediate"],
    ["Overfitting", "Model memorizes training data — poor generalization.", "intermediate"],
    ["Underfitting", "Model too simple to capture patterns.", "intermediate"],
    ["Regularization", "Penalty preventing overly complex models (L1, L2).", "advanced"],
    ["Gradient Descent", "Optimize by stepping opposite loss gradient.", "advanced"],
    ["Learning Rate", "Step size in gradient descent — too high diverges.", "advanced"],
    ["Epoch", "One full pass through training dataset.", "intermediate"],
    ["Batch Size", "Number of samples per gradient update.", "intermediate"],
    ["Mini-Batch", "Subset of data per update balancing speed and noise.", "intermediate"],
    ["Stochastic Gradient Descent", "Update per single sample — noisy but fast.", "advanced"],
    ["Backpropagation", "Compute gradients through network layers via chain rule.", "advanced"],
    ["Activation Function", "Nonlinearity after weighted sum (ReLU, sigmoid, tanh).", "advanced"],
    ["ReLU", "Rectified Linear Unit — max(0, x) common hidden activation.", "advanced"],
    ["Softmax", "Normalize logits to probability distribution summing to 1.", "advanced"],
    ["Cross-Entropy Loss", "Classification loss measuring predicted vs true distribution.", "advanced"],
    ["Mean Squared Error", "Regression loss — average squared prediction error.", "intermediate"],
    ["Precision", "Of predicted positives, fraction actually positive.", "intermediate"],
    ["Recall", "Of actual positives, fraction correctly predicted.", "intermediate"],
    ["F1 Score", "Harmonic mean of precision and recall.", "intermediate"],
    ["Confusion Matrix", "Table of TP, FP, TN, FN classification outcomes.", "intermediate"],
    ["ROC Curve", "True positive rate vs false positive rate at thresholds.", "advanced"],
    ["AUC", "Area Under ROC Curve — overall classifier quality.", "advanced"],
    ["Embedding", "Dense vector representing discrete item (word, user).", "advanced"],
    ["Tokenization", "Split text into tokens for model input.", "intermediate"],
    ["Transformer", "Attention-based architecture powering modern LLMs.", "advanced"],
    ["Attention Mechanism", "Weight input parts by relevance to current output.", "advanced"],
    ["Self-Attention", "Sequence attends to itself — core of Transformers.", "advanced"],
    ["Fine-Tuning", "Adapt pre-trained model to specific task with smaller dataset.", "advanced"],
    ["Transfer Learning", "Reuse knowledge from one task on another.", "advanced"],
    ["Prompt Engineering", "Craft inputs guiding LLM output quality.", "intermediate"],
    ["RAG", "Retrieval-Augmented Generation — fetch docs then generate answer.", "advanced"],
    ["Hallucination", "Model confidently generates false information.", "intermediate"],
    ["Temperature", "Sampling randomness — higher more creative, lower more deterministic.", "intermediate"],
    ["Top-p Sampling", "Nucleus sampling — sample from smallest set covering probability p.", "advanced"],
    ["Inference", "Run trained model on new data to get predictions.", "intermediate"],
    ["Model Quantization", "Reduce weight precision (FP32 to INT8) for speed/size.", "advanced"],
    ["ONNX", "Open Neural Network Exchange — portable model format.", "advanced"],
    ["TensorFlow", "Google open-source ML framework.", "intermediate"],
    ["PyTorch", "Facebook ML framework popular in research.", "intermediate"],
    ["scikit-learn", "Python classical ML library — trees, SVM, clustering.", "intermediate"],
    ["Pandas", "Python data analysis with DataFrame tables.", "intermediate"],
    ["NumPy", "Python numerical arrays and linear algebra.", "intermediate"],
    ["Jupyter Notebook", "Interactive cells mixing code, output, and markdown.", "beginner"],
    ["DataFrame", "Tabular labeled data structure (rows and columns).", "intermediate"],
    ["Feature Engineering", "Create informative inputs from raw data.", "intermediate"],
    ["One-Hot Encoding", "Represent category as binary vector with one bit set.", "intermediate"],
    ["Normalization", "Scale features to comparable range (0-1 or z-score).", "intermediate"],
    ["K-Means Clustering", "Partition data into K groups by centroid distance.", "intermediate"],
    ["Decision Tree", "Tree of if-else splits predicting class or value.", "intermediate"],
    ["Random Forest", "Ensemble of decision trees voting on outcome.", "intermediate"],
    ["Gradient Boosting", "Sequential trees correcting previous errors (XGBoost).", "advanced"],
    ["Support Vector Machine", "Find hyperplane maximizing margin between classes.", "advanced"],
    ["Naive Bayes", "Probabilistic classifier assuming feature independence.", "intermediate"],
    ["K-Nearest Neighbors", "Classify by majority vote of K closest training points.", "intermediate"],
  ];
  for (const [term, definition, level] of aiTerms) {
    add(term, definition, "ai", ["ai", "ml"], level);
  }

  const gitTerms = [
    ["git init", "Create new empty Git repository in current directory.", "beginner"],
    ["git clone", "Copy remote repository including full history.", "beginner"],
    ["git add", "Stage file changes for next commit.", "beginner"],
    ["git commit", "Record staged snapshot with message.", "beginner"],
    ["git push", "Upload local commits to remote repository.", "beginner"],
    ["git pull", "Fetch and merge remote changes into current branch.", "beginner"],
    ["git fetch", "Download remote commits without merging.", "intermediate"],
    ["git merge", "Combine branch history into current branch.", "intermediate"],
    ["git rebase", "Replay commits on top of another base — linear history.", "advanced"],
    ["git checkout", "Switch branches or restore files (git switch in modern Git).", "beginner"],
    ["git branch", "List, create, or delete branches.", "beginner"],
    ["git status", "Show working tree and staging area state.", "beginner"],
    ["git log", "Display commit history.", "beginner"],
    ["git diff", "Show unstaged or staged changes.", "beginner"],
    ["git stash", "Temporarily shelve uncommitted changes.", "intermediate"],
    ["git cherry-pick", "Apply specific commit onto current branch.", "advanced"],
    ["git reset", "Move branch pointer — soft/mixed/hard variants.", "advanced"],
    ["git revert", "Create new commit undoing previous commit safely.", "intermediate"],
    ["git tag", "Mark specific commit as release milestone.", "intermediate"],
    ["git remote", "Manage connections to other repositories.", "intermediate"],
    ["git bisect", "Binary search commits to find bug introduction.", "advanced"],
    ["git blame", "Show who last modified each line.", "intermediate"],
    ["git submodule", "Embed another repository at fixed commit.", "advanced"],
    ["git worktree", "Checkout multiple branches in separate directories.", "advanced"],
    [".gitignore", "File listing paths Git should not track.", "beginner"],
    ["Detached HEAD", "Checkout specific commit not on branch tip.", "intermediate"],
    ["Fast-Forward Merge", "Move branch pointer forward when no divergent commits.", "intermediate"],
    ["Merge Commit", "Commit with two parents combining diverged branches.", "intermediate"],
    ["Interactive Rebase", "Edit, squash, reorder commits during rebase.", "advanced"],
    ["Squash Merge", "Combine all branch commits into one on merge.", "intermediate"],
    ["Git Flow", "Branching model with develop, release, hotfix branches.", "intermediate"],
    ["GitHub Flow", "Simple main + feature branches with PRs.", "beginner"],
    ["Conventional Commits", "Structured messages: feat:, fix:, chore:, etc.", "intermediate"],
  ];
  for (const [term, definition, level] of gitTerms) {
    add(term, definition, "tools", ["git", "version-control"], level);
  }

  const htmlElements = [
    "html", "head", "body", "title", "meta", "link", "script", "style", "noscript",
    "header", "nav", "main", "footer", "section", "article", "aside", "h1", "h2", "h3",
    "h4", "h5", "h6", "p", "div", "span", "a", "img", "video", "audio", "source",
    "canvas", "svg", "table", "thead", "tbody", "tr", "th", "td", "form", "input",
    "textarea", "button", "select", "option", "label", "fieldset", "legend", "ul", "ol",
    "li", "dl", "dt", "dd", "figure", "figcaption", "blockquote", "pre", "code", "em",
    "strong", "br", "hr", "iframe", "details", "summary", "dialog", "template", "slot",
  ];
  const htmlDefs = {
    html: "Root element of HTML document.",
    head: "Container for metadata not displayed on page.",
    body: "Visible content of the document.",
    a: "Anchor — hyperlink to another resource.",
    img: "Embed image referenced by src URL.",
    form: "Interactive controls submitting data to server.",
    input: "Generic input control — type attribute sets behavior.",
    canvas: "Bitmap drawing surface for JavaScript graphics.",
    svg: "Scalable Vector Graphics embedded in page.",
  };
  for (const el of htmlElements) {
    add(
      `<${el}> element`,
      htmlDefs[el] || `HTML ${el} element — part of the HTML living standard for document structure or semantics.`,
      "web",
      ["html", "markup"],
      "beginner"
    );
  }

  const cssProps = [
    ["display", "How element generates boxes — block, flex, grid, none."],
    ["position", "Positioning scheme — static, relative, absolute, fixed, sticky."],
    ["flex-direction", "Main axis direction in flex container — row or column."],
    ["justify-content", "Align flex items along main axis."],
    ["align-items", "Align flex items along cross axis."],
    ["grid-template-columns", "Define column tracks in CSS Grid."],
    ["grid-template-rows", "Define row tracks in CSS Grid."],
    ["gap", "Spacing between grid/flex items."],
    ["margin", "Outer spacing outside element border."],
    ["padding", "Inner spacing between content and border."],
    ["border", "Line around padding edge."],
    ["width", "Horizontal size of content area."],
    ["height", "Vertical size of content area."],
    ["box-sizing", "Whether width includes padding/border (border-box)."],
    ["overflow", "Behavior when content exceeds box — hidden, scroll, auto."],
    ["z-index", "Stacking order of positioned elements."],
    ["opacity", "Transparency 0–1 of entire element."],
    ["visibility", "hidden keeps layout; display:none removes from flow."],
    ["color", "Foreground text color."],
    ["background-color", "Fill color behind content."],
    ["background-image", "Image or gradient behind content."],
    ["font-family", "Typeface stack for text."],
    ["font-size", "Text size — px, rem, em, etc."],
    ["font-weight", "Boldness — 100–900 or normal/bold."],
    ["line-height", "Vertical space between lines of text."],
    ["text-align", "Horizontal alignment — left, center, right, justify."],
    ["text-decoration", "Underline, line-through, etc."],
    ["cursor", "Mouse pointer appearance over element."],
    ["transition", "Animate property changes over duration."],
    ["animation", "Apply named @keyframes animation."],
    ["transform", "Rotate, scale, translate without layout reflow."],
    ["filter", "Visual effects — blur, brightness, contrast."],
    ["box-shadow", "Drop shadow around element box."],
    ["border-radius", "Rounded corners of border box."],
    ["object-fit", "How replaced content (img/video) fits box."],
    ["aspect-ratio", "Preferred width-to-height ratio."],
    ["min-width", "Minimum horizontal size constraint."],
    ["max-width", "Maximum horizontal size constraint."],
    ["min-height", "Minimum vertical size constraint."],
    ["max-height", "Maximum vertical size constraint."],
    ["flex-wrap", "Whether flex items wrap to new line."],
    ["flex-grow", "How much item grows relative to siblings."],
    ["flex-shrink", "How much item shrinks when space tight."],
    ["flex-basis", "Initial main size before grow/shrink."],
    ["order", "Visual order of flex/grid item."],
    ["grid-area", "Shorthand for grid row/column placement."],
    ["grid-column", "Which grid columns item spans."],
    ["grid-row", "Which grid rows item spans."],
    ["place-items", "Shorthand align-items + justify-items in grid."],
    ["place-content", "Align entire grid within container."],
    ["float", "Legacy wrap text around element — prefer flex/grid."],
    ["clear", "Clear floats on left/right/both sides."],
    ["vertical-align", "Align inline/ table-cell content vertically."],
    ["white-space", "Line wrapping and space collapsing behavior."],
    ["word-break", "How words break at line boundaries."],
    ["overflow-wrap", "Break long words preventing overflow."],
    ["text-overflow", "Ellipsis when text clipped (with overflow hidden)."],
    ["user-select", "Whether user can select text."],
    ["pointer-events", "Whether element receives mouse events."],
    ["will-change", "Hint browser to optimize upcoming property changes."],
    ["contain", "Limit layout/paint/style recalc scope for performance."],
    ["content", "Generated content in ::before/::after pseudo-elements."],
    ["var()", "Use CSS custom property value."],
    ["calc()", "Compute value from expression (+, -, *, /)."],
    ["clamp()", "Value constrained between min and max."],
    ["@media", "Apply rules when media conditions match (responsive)."],
    ["@keyframes", "Define steps of CSS animation."],
    ["@import", "Import another stylesheet."],
    ["@font-face", "Define custom web font family."],
    [":hover", "Pseudo-class when pointer over element."],
    [":focus", "Pseudo-class when element has keyboard focus."],
    [":active", "Pseudo-class while element being activated."],
    ["::before", "Pseudo-element inserted before element content."],
    ["::after", "Pseudo-element inserted after element content."],
  ];
  for (const [prop, definition] of cssProps) {
    const name = prop.startsWith(":") || prop.startsWith("@") ? prop : `CSS ${prop}`;
    add(name, definition, "web", ["css", "styling"], "beginner");
  }

  const complexities = [
    ["O(1) Constant Time", "Runtime independent of input size — hash lookup average case."],
    ["O(log n) Logarithmic Time", "Halving problem each step — binary search."],
    ["O(n) Linear Time", "Proportional to input size — single loop."],
    ["O(n log n) Linearithmic Time", "Efficient sorts like merge sort."],
    ["O(n²) Quadratic Time", "Nested loops over input — naive sort comparisons."],
    ["O(n³) Cubic Time", "Triple nested loops — naive matrix multiply."],
    ["O(2ⁿ) Exponential Time", "Doubling branches — brute force subsets."],
    ["O(n!) Factorial Time", "Permutation enumeration — traveling salesman brute force."],
    ["O(√n) Square Root Time", "Some number theory algorithms."],
    ["Amortized O(1)", "Average constant time over sequence — dynamic array push."],
    ["Worst Case Complexity", "Upper bound on runtime for any input of size n."],
    ["Average Case Complexity", "Expected runtime over random inputs."],
    ["Best Case Complexity", "Most favorable input scenario — often not useful alone."],
    ["Space Complexity", "Memory usage as function of input size."],
    ["Auxiliary Space", "Extra memory beyond input storage."],
    ["In-Place Algorithm", "Uses O(1) extra space modifying input."],
  ];
  for (const [term, definition] of complexities) {
    add(term, definition, "algorithms", ["complexity", "big-o"], "intermediate");
  }

  const formats = [
    [".json", "JSON text data — objects and arrays.", "formats"],
    [".yaml / .yml", "Human-readable config serialization.", "formats"],
    [".xml", "Tagged hierarchical markup.", "formats"],
    [".csv", "Comma-separated tabular values.", "formats"],
    [".tsv", "Tab-separated tabular values.", "formats"],
    [".md", "Markdown plain-text formatting.", "formats"],
    [".html / .htm", "HyperText Markup web documents.", "formats"],
    [".css", "Stylesheet for HTML.", "formats"],
    [".js / .mjs / .cjs", "JavaScript source modules.", "formats"],
    [".ts", "TypeScript source requiring compilation.", "formats"],
    [".tsx / .jsx", "TypeScript/JSX or JavaScript/JSX React components.", "formats"],
    [".py", "Python source code.", "formats"],
    [".java", "Java source code.", "formats"],
    [".c / .h", "C source and header files.", "formats"],
    [".cpp / .hpp", "C++ source and headers.", "formats"],
    [".rs", "Rust source code.", "formats"],
    [".go", "Go source code.", "formats"],
    [".rb", "Ruby source code.", "formats"],
    [".php", "PHP server-side script.", "formats"],
    [".swift", "Swift Apple platform source.", "formats"],
    [".kt", "Kotlin JVM/Android source.", "formats"],
    [".sql", "SQL scripts and queries.", "formats"],
    [".sh", "Shell script (bash).", "formats"],
    [".ps1", "PowerShell script.", "formats"],
    [".bat / .cmd", "Windows batch script.", "formats"],
    [".exe", "Windows executable binary.", "formats"],
    [".dll", "Dynamic link library — shared Windows code.", "formats"],
    [".so", "Shared object — Unix dynamic library.", "formats"],
    [".a", "Static library archive.", "formats"],
    [".wasm", "WebAssembly binary module.", "formats"],
    [".png", "Lossless raster image with alpha.", "formats"],
    [".jpg / .jpeg", "Lossy photo compression.", "formats"],
    [".gif", "Palette image supporting animation.", "formats"],
    [".svg", "XML vector graphics.", "formats"],
    [".webp", "Modern web image format.", "formats"],
    [".ico", "Windows icon file.", "formats"],
    [".mp3", "Compressed audio.", "formats"],
    [".wav", "Uncompressed PCM audio.", "formats"],
    [".mp4", "Video container (H.264 common).", "formats"],
    [".zip", "Compressed archive.", "formats"],
    [".tar", "Tape archive bundling files.", "formats"],
    [".gz", "Gzip single-file compression.", "formats"],
    [".7z", "High compression archive.", "formats"],
    [".pdf", "Portable fixed-layout documents.", "formats"],
    [".docx", "Office Open XML Word document.", "formats"],
    [".xlsx", "Excel spreadsheet.", "formats"],
    [".env", "Environment variable key=value file.", "formats"],
    [".gitignore", "Git untracked path patterns.", "formats"],
    [".dockerignore", "Docker build context exclusions.", "formats"],
    [".lock file", "Pinned dependency versions (package-lock.json, yarn.lock).", "formats"],
  ];
  for (const [term, definition, category] of formats) {
    add(`File format ${term}`, definition, category, ["file", "format"], "beginner");
  }

  const patternTemplates = [
    ["Anti-pattern", "Common bad solution to recurring problem — avoid in production.", "architecture"],
    ["Code pattern", "Reusable solution to recurring design problem in code.", "architecture"],
    ["Integration pattern", "Standard way to connect heterogeneous systems.", "architecture"],
    ["Messaging pattern", "Structure for async communication between services.", "architecture"],
    ["Caching pattern", "Strategy for storing computed data for faster reuse.", "architecture"],
  ];

  const domains = [
    "authentication", "authorization", "logging", "monitoring", "deployment", "rollback",
    "canary release", "blue-green deployment", "feature flag", "A/B testing", "load balancing",
    "health check", "graceful shutdown", "circuit breaking", "retry with backoff", "idempotency key",
    "correlation ID", "structured logging", "log aggregation", "metrics cardinality",
    "histogram metric", "counter metric", "gauge metric", "summary metric", "distributed tracing",
    "span context", "trace ID", "parent span", "sampling rate", "tail-based sampling",
    "service discovery", "config server", "secret rotation", "certificate renewal", "mTLS handshake",
    "API gateway", "reverse proxy", "forward proxy", "CDN cache hit", "CDN cache miss",
    "cache invalidation", "TTL expiration", "write-through cache", "write-back cache", "cache aside",
    "read replica", "failover", "active-active", "active-passive", "disaster recovery",
    "cold standby", "hot standby", "backup retention", "point-in-time recovery", "immutable backup",
    "object storage", "block storage", "file storage", "NVMe", "iops",
    "throughput", "latency percentile", "p50 latency", "p95 latency", "p99 latency",
    "error budget", "toil reduction", "runbook", "playbook", "incident commander",
    "postmortem", "blameless culture", "root cause analysis", "five whys", "fishbone diagram",
    "capacity planning", "autoscaling", "horizontal scaling", "vertical scaling", "noisy neighbor",
    "multi-tenancy", "single-tenancy", "tenant isolation", "data residency", "GDPR compliance",
    "PII", "data anonymization", "pseudonymization", "right to erasure", "consent management",
    "access token", "refresh token", "token expiry", "scope limitation", "OAuth consent screen",
    "password hashing", "MFA", "TOTP", "WebAuthn", "passkey",
    "RBAC", "ABAC", "ACL", "policy engine", "least privilege audit",
  ];

  for (const d of domains) {
    const title = d.split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
    add(
      title,
      `Concept in software engineering related to ${d} — important for building reliable, secure, and scalable systems.`,
      d.includes("cache") || d.includes("CDN") ? "devops" : d.includes("OAuth") || d.includes("MFA") || d.includes("GDPR") ? "security" : "architecture",
      [d.replace(/\s+/g, "-")],
      "intermediate"
    );
  }

  const languages = [
    ["JavaScript", "Dynamic language of the web — runs in browsers and Node.js.", "languages"],
    ["TypeScript", "Typed superset of JavaScript compiling to JS.", "languages"],
    ["Python", "High-level language known for readability and vast ecosystem.", "languages"],
    ["Java", "Statically typed JVM language for enterprise and Android.", "languages"],
    ["C", "Low-level systems language — foundation of Unix and OS kernels.", "languages"],
    ["C++", "C with OOP and templates — games, browsers, systems.", "languages"],
    ["C#", "Microsoft .NET language for Windows, web, and Unity games.", "languages"],
    ["Go", "Google language for simple concurrent network services.", "languages"],
    ["Rust", "Memory-safe systems language without garbage collector.", "languages"],
    ["Ruby", "Dynamic expressive language — Rails web framework.", "languages"],
    ["PHP", "Server-side web scripting language.", "languages"],
    ["Swift", "Apple modern language for iOS, macOS, watchOS.", "languages"],
    ["Kotlin", "JVM language preferred for Android development.", "languages"],
    ["Scala", "JVM functional-OOP hybrid on Spark big data.", "languages"],
    ["Haskell", "Pure functional language with strong static types.", "languages"],
    ["Erlang", "Fault-tolerant concurrent language — telecom and WhatsApp.", "languages"],
    ["Elixir", "Modern BEAM VM language built on Erlang OTP.", "languages"],
    ["Clojure", "Lisp dialect on JVM with immutable data focus.", "languages"],
    ["Lua", "Embeddable scripting in games and Redis.", "languages"],
    ["R", "Statistical computing and visualization language.", "languages"],
    ["MATLAB", "Numerical computing for engineering and science.", "languages"],
    ["Dart", "Language behind Flutter cross-platform UI.", "languages"],
    ["Objective-C", "Legacy Apple language before Swift.", "languages"],
    ["Assembly", "Human-readable low-level CPU mnemonics.", "languages"],
    ["WebAssembly", "Portable bytecode for browsers and beyond.", "languages"],
    ["Solidity", "Smart contract language for Ethereum.", "languages"],
    ["COBOL", "Legacy business language still in banking mainframes.", "languages"],
    ["Fortran", "Scientific computing language since 1950s.", "languages"],
    ["Perl", "Text processing and early web scripting.", "languages"],
    ["Shell Script", "Automate Unix commands in bash/zsh.", "languages"],
    ["PowerShell", "Microsoft object-oriented shell and scripting.", "languages"],
    ["VBA", "Visual Basic for Applications in Office macros.", "languages"],
    ["SQL", "Declarative language for relational database queries.", "languages"],
    ["GraphQL Schema Language", "Define types and operations for GraphQL API.", "languages"],
    ["Protocol Buffers", "Google binary serialization IDL (.proto files).", "languages"],
    ["HTML", "Markup language structuring web documents.", "languages"],
    ["CSS", "Stylesheet language for presentation.", "languages"],
  ];
  for (const [term, definition, category] of languages) {
    add(term, definition, category, ["language"], "beginner");
  }

  const webApis = [
    "fetch", "localStorage", "sessionStorage", "indexedDB", "WebSocket", "Worker", "ServiceWorker",
    "Notification", "Geolocation", "IntersectionObserver", "MutationObserver", "ResizeObserver",
    "requestAnimationFrame", "cancelAnimationFrame", "setTimeout", "setInterval", "Promise",
    "async/await", "EventTarget", "addEventListener", "CustomEvent", "AbortController",
    "URLSearchParams", "FormData", "Blob", "FileReader", "CanvasRenderingContext2D",
    "WebGL", "AudioContext", "MediaStream", "getUserMedia", "Clipboard API", "Share API",
    "History API", "pushState", "replaceState", "matchMedia", "Intl", "structuredClone",
    "crypto.subtle", "TextEncoder", "TextDecoder", "ReadableStream", "WritableStream",
    "TransformStream", "BroadcastChannel", "MessageChannel", "Performance API", "Navigation Timing",
  ];
  for (const api of webApis) {
    add(
      `Web API: ${api}`,
      `Browser ${api} API — part of Web platform exposing capabilities to JavaScript in supporting browsers.`,
      "web",
      ["web-api", "browser", "javascript"],
      "intermediate"
    );
  }

  const errors = [
    ["SyntaxError", "Invalid JavaScript syntax — parse time failure.", "languages"],
    ["TypeError", "Operation on wrong type — undefined is not a function.", "languages"],
    ["ReferenceError", "Access undeclared variable.", "languages"],
    ["RangeError", "Numeric value out of allowed range.", "languages"],
    ["URIError", "Malformed URI handling functions.", "languages"],
    ["EvalError", "Legacy error from eval misuse.", "languages"],
    ["AggregateError", "Wraps multiple errors from Promise.any rejection.", "languages"],
    ["StackOverflowError", ".NET too deep recursion.", "languages"],
    ["NullReferenceException", "C#/Java dereference null object.", "languages"],
    ["IndexOutOfBoundsException", "Array/list index outside valid range.", "languages"],
    ["IOException", "Input/output operation failed.", "os"],
    ["FileNotFoundException", "Requested file path does not exist.", "os"],
    ["OutOfMemoryError", "JVM heap exhausted.", "os"],
    ["Segmentation Fault", "Invalid memory access — native code crash.", "os"],
    ["Kernel Panic", "Fatal unrecoverable OS error.", "os"],
    ["Blue Screen of Death", "Windows critical system failure stop code.", "os"],
  ];
  for (const [term, definition, category] of errors) {
    add(term, definition, category, ["error", "debugging"], "intermediate");
  }

  const mobile = [
    ["React Native", "Build mobile apps using React targeting iOS and Android.", "mobile"],
    ["Flutter", "Google UI toolkit with Dart compiling to native ARM.", "mobile"],
    ["SwiftUI", "Declarative Apple UI framework.", "mobile"],
    ["Jetpack Compose", "Modern declarative Android UI in Kotlin.", "mobile"],
    ["Xcode", "Apple IDE for iOS/macOS development.", "mobile"],
    ["Android Studio", "Official Android IDE based on IntelliJ.", "mobile"],
    ["App Store", "Apple iOS app distribution marketplace.", "mobile"],
    ["Google Play", "Android app distribution store.", "mobile"],
    ["APK", "Android Package — installable Android app file.", "mobile"],
    ["AAB", "Android App Bundle — Play Store publishing format.", "mobile"],
    ["IPA", "iOS App Store package format.", "mobile"],
    ["Provisioning Profile", "iOS code signing configuration linking app and devices.", "mobile"],
    ["Deep Link", "URL opening specific screen inside mobile app.", "mobile"],
    ["Universal Link", "iOS HTTPS link opening app if installed.", "mobile"],
    ["Push Notification", "Server message displayed on device when app backgrounded.", "mobile"],
    ["FCM", "Firebase Cloud Messaging — Android/iOS push delivery.", "mobile"],
    ["APNs", "Apple Push Notification service.", "mobile"],
    ["In-App Purchase", "Buy digital goods inside mobile app.", "mobile"],
    ["TestFlight", "Apple beta distribution for iOS apps.", "mobile"],
    ["Emulator", "Software simulating mobile device on desktop.", "mobile"],
    ["Simulator", "iOS/macOS simulated device (not full hardware emulation).", "mobile"],
  ];
  for (const [term, definition, category] of mobile) {
    add(term, definition, category, ["mobile"], "intermediate");
  }

  const osTerms = [
    ["Kernel", "Core OS managing CPU, memory, devices, syscalls.", "advanced"],
    ["User Space", "Non-privileged applications run here vs kernel space.", "intermediate"],
    ["System Call", "Interface from user program into kernel services.", "advanced"],
    ["Virtual Memory", "Abstraction giving each process own address space.", "advanced"],
    ["Page Fault", "Access page not in RAM — OS loads from disk.", "advanced"],
    ["Context Switch", "CPU switches from one thread/process to another.", "advanced"],
    ["Scheduler", "OS picks next thread to run on CPU.", "advanced"],
    ["Preemptive Multitasking", "OS forcibly switches tasks on timer interrupt.", "advanced"],
    ["Cooperative Multitasking", "Tasks yield voluntarily — early Mac, coroutines.", "advanced"],
    ["Inode", "Unix file metadata structure — permissions, size, blocks.", "advanced"],
    ["File Descriptor", "Integer handle to open file, socket, or pipe.", "intermediate"],
    ["Pipe", "Unidirectional IPC channel between processes.", "intermediate"],
    ["Signal", "Unix async notification to process (SIGTERM, SIGKILL).", "advanced"],
    ["Daemon", "Background Unix service process.", "intermediate"],
    ["Cron", "Unix job scheduler running commands on timetable.", "intermediate"],
    ["systemd", "Linux init system managing services and boot.", "intermediate"],
    ["Windows Registry", "Hierarchical Windows configuration database.", "intermediate"],
    ["NTFS", "Windows default file system with ACLs and journaling.", "intermediate"],
    ["ext4", "Common Linux journaling file system.", "intermediate"],
    ["APFS", "Apple File System for macOS/iOS.", "intermediate"],
    ["Swap", "Disk space used as extension of RAM.", "intermediate"],
    ["Thrashing", "Excessive paging — system spends time swapping not working.", "advanced"],
  ];
  for (const [term, definition, category] of osTerms) {
    add(term, definition, "os", ["operating-system"], category === "advanced" ? "advanced" : "intermediate");
  }

  const testingTools = [
    ["Jest", "JavaScript test runner with mocking and snapshots.", "testing"],
    ["Vitest", "Vite-native fast unit test runner.", "testing"],
    ["Mocha", "Flexible JavaScript test framework.", "testing"],
    ["Chai", "Assertion library for JavaScript tests.", "testing"],
    ["Cypress", "End-to-end browser testing with time travel debugging.", "testing"],
    ["Playwright", "Cross-browser automation by Microsoft.", "testing"],
    ["Selenium", "Legacy browser automation WebDriver standard.", "testing"],
    ["Puppeteer", "Headless Chrome control via Node API.", "testing"],
    ["pytest", "Python testing framework with fixtures.", "testing"],
    ["unittest", "Python standard library testing module.", "testing"],
    ["JUnit", "Java unit testing framework.", "testing"],
    ["TestNG", "Java testing with parallel and data-driven tests.", "testing"],
    ["RSpec", "Ruby BDD testing framework.", "testing"],
    ["PHPUnit", "PHP unit testing framework.", "testing"],
    ["xUnit", "Family of unit test frameworks (.NET xUnit, etc.).", "testing"],
    ["Mockito", "Java mocking framework.", "testing"],
    ["Sinon", "JavaScript spies, stubs, and mocks.", "testing"],
    ["k6", "Load testing tool scripting in JavaScript.", "testing"],
    ["Locust", "Python distributed load testing.", "testing"],
    ["JMeter", "Apache Java load and performance testing.", "testing"],
  ];
  for (const [term, definition, category] of testingTools) {
    add(term, definition, category, ["testing", "tool"], "intermediate");
  }

  const protocols = [
    "HTTP/1.1", "HTTP/2", "HTTP/3", "QUIC", "TLS 1.2", "TLS 1.3", "WebSocket", "MQTT",
    "AMQP", "STOMP", "gRPC", "Protobuf", "JSON-RPC", "XML-RPC", "SOAP", "REST",
    "GraphQL", "OpenAPI", "Swagger", "AsyncAPI", "OAuth 2.0", "OIDC", "SAML 2.0",
    "LDAP", "Kerberos", "RADIUS", "BGP", "OSPF", "VLAN", "VPN", "IPsec", "NAT",
    "DHCP", "ARP", "ICMP", "DNSSEC", "DoH", "DoT", "mDNS", "Bonjour", "SSDP",
    "NTP", "SNTP", "FTP", "FTPS", "SFTP", "SMB", "NFS", "iSCSI", "SCSI", "PCIe",
    "USB", "Thunderbolt", "HDMI", "DisplayPort", "Bluetooth", "BLE", "Wi-Fi 6",
    "802.11ax", "Ethernet", "MAC address", "IPv4", "IPv6", "CIDR", "subnet mask",
    "default gateway", "loopback", "localhost", "127.0.0.1", "::1",
  ];
  for (const p of protocols) {
    add(
      `${p} protocol`,
      `${p} — networking or communication standard used in computer systems and software integration.`,
      "networking",
      ["protocol", "network"],
      "intermediate"
    );
  }

  const nodeTerms = [
    ["Node.js", "JavaScript runtime built on V8 for server and tooling.", "tools"],
    ["V8", "Google JavaScript engine in Chrome and Node.", "tools"],
    ["libuv", "Cross-platform async I/O library powering Node event loop.", "tools"],
    ["Event Loop", "Node mechanism scheduling callbacks and I/O completion.", "tools"],
    ["npm registry", "Public package repository for JavaScript.", "tools"],
    ["package.json", "Node project manifest — dependencies and scripts.", "tools"],
    ["node_modules", "Folder where npm installs dependency packages.", "tools"],
    ["CommonJS", "require/module.exports Node module system.", "tools"],
    ["ES Modules", "import/export standard module system.", "tools"],
    ["Electron", "Build desktop apps with web tech and Node in Chromium.", "tools"],
    ["Chromium", "Open-source browser engine base of Chrome and Electron.", "tools"],
    ["contextBridge", "Electron safe API exposure from preload to renderer.", "tools"],
    ["ipcMain", "Electron main process IPC listener.", "tools"],
    ["ipcRenderer", "Electron renderer process IPC sender.", "tools"],
    ["BrowserWindow", "Electron class creating application window.", "tools"],
    ["webview tag", "Embed web content in Electron with separate process.", "tools"],
    ["process.env", "Node object holding environment variables.", "tools"],
    ["__dirname", "CommonJS directory path of current module.", "tools"],
    ["import.meta", "ESM meta information including import.meta.url.", "tools"],
  ];
  for (const [term, definition, category] of nodeTerms) {
    add(term, definition, category, ["nodejs", "electron"], "intermediate");
  }

  return entries;
}

module.exports = { curatedEntries };
