const CATEGORIES = {
  web: { id: "web", label: "Web Development", icon: "🌐" },
  languages: { id: "languages", label: "Programming Languages", icon: "💻" },
  algorithms: { id: "algorithms", label: "Algorithms & Data Structures", icon: "🧮" },
  databases: { id: "databases", label: "Databases", icon: "🗄️" },
  devops: { id: "devops", label: "DevOps & Cloud", icon: "☁️" },
  security: { id: "security", label: "Security", icon: "🔒" },
  networking: { id: "networking", label: "Networking", icon: "🔗" },
  architecture: { id: "architecture", label: "Architecture & Patterns", icon: "🏛️" },
  testing: { id: "testing", label: "Testing & Quality", icon: "🧪" },
  tools: { id: "tools", label: "Tools & Ecosystem", icon: "🛠️" },
  fundamentals: { id: "fundamentals", label: "CS Fundamentals", icon: "📐" },
  ai: { id: "ai", label: "AI & Data Science", icon: "🤖" },
  mobile: { id: "mobile", label: "Mobile Development", icon: "📱" },
  os: { id: "os", label: "Operating Systems", icon: "🖥️" },
  formats: { id: "formats", label: "Formats & Protocols", icon: "📄" },
};

function slugify(text) {
  return String(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function addEntries(list, entries) {
  for (const e of entries) list.push(e);
}

function httpStatusCodes() {
  const known = {
    100: "Continue: the client may continue the request; used for expect-100-continue handshakes.",
    101: "Switching Protocols: server agrees to change protocol (e.g. WebSocket upgrade).",
    102: "Processing: request accepted; server still processing (WebDAV).",
    103: "Early Hints: interim response with Link headers before final response.",
    200: "OK: request succeeded; response body contains the result.",
    201: "Created: resource was created successfully (common after POST).",
    202: "Accepted: request accepted for processing but not yet completed.",
    204: "No Content: success with no response body (common for DELETE).",
    206: "Partial Content: range request fulfilled; used for downloads and streaming.",
    301: "Moved Permanently: resource permanently moved to a new URL.",
    302: "Found: temporary redirect to another URL.",
    304: "Not Modified: cached version is still valid (conditional GET).",
    307: "Temporary Redirect: redirect without changing HTTP method.",
    308: "Permanent Redirect: permanent redirect preserving HTTP method.",
    400: "Bad Request: malformed syntax or invalid parameters.",
    401: "Unauthorized: authentication required or failed.",
    403: "Forbidden: authenticated but not allowed to access resource.",
    404: "Not Found: resource does not exist at this URL.",
    405: "Method Not Allowed: HTTP verb not supported for this endpoint.",
    408: "Request Timeout: server timed out waiting for client request.",
    409: "Conflict: request conflicts with current state (e.g. duplicate).",
    410: "Gone: resource permanently removed and will not return.",
    413: "Payload Too Large: request body exceeds server limit.",
    415: "Unsupported Media Type: Content-Type not supported.",
    418: "I'm a teapot: RFC 2324 joke status; sometimes used in demos.",
    422: "Unprocessable Entity: validation failed on well-formed JSON.",
    429: "Too Many Requests: rate limit exceeded; retry after backoff.",
    500: "Internal Server Error: unexpected server failure.",
    501: "Not Implemented: server does not support this capability.",
    502: "Bad Gateway: invalid response from upstream server.",
    503: "Service Unavailable: server overloaded or in maintenance.",
    504: "Gateway Timeout: upstream server did not respond in time.",
  };
  const out = [];
  for (let code = 100; code <= 599; code++) {
    const family = Math.floor(code / 100);
    const families = ["Informational", "Success", "Redirection", "Client Error", "Server Error"];
    const def =
      known[code] ||
      `HTTP ${code} — ${families[family - 1] || "Unknown"} status code in the HTTP protocol specification.`;
    out.push({
      term: `HTTP ${code}`,
      definition: def,
      category: "formats",
      tags: ["http", "web", "status"],
      level: code >= 500 ? "intermediate" : "beginner",
    });
  }
  return out;
}

function wellKnownPorts() {
  const ports = {
    20: "FTP data transfer channel.",
    21: "FTP control channel for file transfer protocol.",
    22: "SSH: secure shell remote login and file transfer.",
    23: "Telnet: unencrypted remote terminal (legacy, insecure).",
    25: "SMTP: sending email between mail servers.",
    53: "DNS: domain name resolution over UDP/TCP.",
    67: "DHCP server: assigns IP addresses to clients.",
    68: "DHCP client: receives IP configuration.",
    80: "HTTP: unencrypted web traffic.",
    110: "POP3: retrieve email from a mail server.",
    123: "NTP: network time synchronization.",
    143: "IMAP: email access keeping messages on server.",
    443: "HTTPS: encrypted web traffic over TLS.",
    465: "SMTPS: SMTP over implicit TLS.",
    587: "SMTP submission: mail clients sending email (STARTTLS).",
    993: "IMAPS: IMAP over TLS.",
    995: "POP3S: POP3 over TLS.",
    1433: "Microsoft SQL Server default port.",
    1521: "Oracle Database listener port.",
    3306: "MySQL / MariaDB default port.",
    3389: "RDP: Remote Desktop Protocol for Windows.",
    5432: "PostgreSQL default port.",
    5672: "AMQP: message queue protocol (RabbitMQ).",
    6379: "Redis: in-memory data store default port.",
    8080: "Alternative HTTP port: proxies and dev servers.",
    8443: "Alternative HTTPS port for admin panels.",
    9200: "Elasticsearch HTTP API default port.",
    27017: "MongoDB default port.",
  };
  return Object.entries(ports).map(([port, definition]) => ({
    term: `Port ${port}`,
    definition,
    category: "networking",
    tags: ["port", "tcp", "network"],
    level: "intermediate",
  }));
}

function mimeTypes() {
  const types = {
    "application/json": "JSON data: standard format for REST APIs and config files.",
    "application/xml": "XML document: structured markup for enterprise and legacy APIs.",
    "application/pdf": "Portable Document Format: fixed-layout documents.",
    "application/zip": "ZIP archive: compressed bundle of files.",
    "application/octet-stream": "Generic binary blob: download/upload when type is unknown.",
    "application/javascript": "JavaScript source code (legacy MIME; text/javascript also used).",
    "application/wasm": "WebAssembly binary module for near-native browser performance.",
    "text/html": "HTML document: structure of web pages.",
    "text/css": "Cascading Style Sheets: presentation of HTML.",
    "text/plain": "Unformatted plain text.",
    "text/csv": "Comma-separated values: tabular data export.",
    "text/markdown": "Markdown formatted text: lightweight markup.",
    "image/png": "PNG raster image: lossless with transparency.",
    "image/jpeg": "JPEG image: lossy compression for photos.",
    "image/svg+xml": "SVG vector image: scalable XML graphics.",
    "image/webp": "WebP image: modern web format with good compression.",
    "image/gif": "GIF image: supports animation and limited palette.",
    "audio/mpeg": "MP3 audio stream.",
    "video/mp4": "MP4 video container (H.264/H.265 common).",
    "multipart/form-data": "HTML form encoding for file uploads.",
    "application/x-www-form-urlencoded": "Default HTML form encoding as key=value pairs.",
  };
  return Object.entries(types).map(([mime, definition]) => ({
    term: `MIME type ${mime}`,
    definition,
    category: "formats",
    tags: ["mime", "http", "content-type"],
    level: "beginner",
  }));
}

function languageKeywords() {
  const langs = {
    JavaScript: {
      category: "languages",
      tags: ["javascript", "ecmascript"],
      words: {
        async: "Declares an asynchronous function that returns a Promise and allows await inside.",
        await: "Pauses async function execution until a Promise settles.",
        break: "Exits the nearest loop or switch statement.",
        case: "Labels a branch inside a switch statement.",
        catch: "Handles exceptions thrown in the paired try block.",
        class: "Defines a constructor function with prototype methods using class syntax.",
        const: "Declares a block-scoped constant binding that cannot be reassigned.",
        continue: "Skips to the next iteration of the current loop.",
        debugger: "Inserts a breakpoint for debugging tools.",
        default: "Marks the fallback branch in switch or default export in modules.",
        delete: "Removes a property from an object.",
        do: "Executes a loop body at least once, then checks condition.",
        else: "Alternative branch when if condition is false.",
        export: "Exposes bindings from an ES module to importers.",
        extends: "Creates a subclass inheriting from a parent class.",
        finally: "Runs after try/catch regardless of outcome.",
        for: "Loop with initialization, condition, and increment expressions.",
        function: "Declares a reusable function (or function expression).",
        if: "Conditional execution when expression is truthy.",
        import: "Loads bindings exported from another ES module.",
        in: "Checks property existence or iterates object keys in for-in loops.",
        instanceof: "Tests whether an object inherits from a constructor's prototype.",
        let: "Declares block-scoped variable allowing reassignment.",
        new: "Creates an instance by calling a constructor function.",
        return: "Exits a function and optionally passes a value back.",
        static: "Defines class members belonging to the class itself, not instances.",
        super: "Calls parent class constructor or methods in a subclass.",
        switch: "Multi-branch control flow comparing one value to many cases.",
        this: "Refers to the execution context object (depends on call site).",
        throw: "Raises an exception to be caught by try/catch or propagate.",
        try: "Wraps code that may throw; paired with catch/finally.",
        typeof: "Returns a string naming the primitive type of a value.",
        var: "Declares function-scoped or globally-scoped variable (legacy).",
        void: "Evaluates expression and returns undefined.",
        while: "Repeats block while condition is truthy.",
        with: "Deprecated — adds object properties to scope chain (avoid).",
        yield: "Pauses and resumes a generator function, producing values.",
        "null": "Primitive value representing intentional absence of object reference.",
        undefined: "Value of uninitialized variables and missing properties.",
        true: "Boolean literal for truth.",
        false: "Boolean literal for falsity.",
      },
    },
    Python: {
      category: "languages",
      tags: ["python"],
      words: {
        and: "Logical AND operator; also used in compound statements.",
        as: "Alias in import statements or exception binding in except.",
        assert: "Raises AssertionError if condition is false (debug checks).",
        async: "Defines coroutine function for asynchronous I/O.",
        await: "Suspends coroutine until awaitable completes.",
        break: "Exit the nearest enclosing loop.",
        class: "Defines a new class type with attributes and methods.",
        continue: "Skip rest of loop body and go to next iteration.",
        def: "Defines a function or method.",
        del: "Deletes reference to variable, list item, or attribute.",
        elif: "Else-if branch in conditional chain.",
        else: "Alternative branch when if/elif conditions fail.",
        except: "Catches exceptions raised in try block.",
        False: "Boolean false literal (capitalized in Python 3).",
        finally: "Always runs after try/except, even on return.",
        for: "Iterates over sequence or iterable.",
        from: "Import specific names from a module.",
        global: "Declares assignment targets module-level global name.",
        if: "Conditional statement based on truthiness.",
        import: "Load module into current namespace.",
        in: "Membership test or loop iterator.",
        is: "Identity comparison — same object in memory.",
        lambda: "Anonymous inline function expression.",
        None: "Singleton representing absence of value.",
        nonlocal: "Binds assignment to enclosing (non-global) scope.",
        not: "Logical negation operator.",
        or: "Logical OR operator.",
        pass: "No-op placeholder for syntactically required block.",
        raise: "Explicitly raise an exception.",
        return: "Exit function with optional value.",
        True: "Boolean true literal.",
        try: "Start exception handling block.",
        while: "Loop while condition is true.",
        with: "Context manager: setup/teardown via __enter__/__exit__.",
        yield: "Produce value from generator and pause execution.",
      },
    },
    Rust: {
      category: "languages",
      tags: ["rust", "systems"],
      words: {
        async: "Marks async fn returning impl Future for cooperative multitasking.",
        await: "Polls Future until Ready inside async context.",
        break: "Exit loop or labeled loop with optional value.",
        const: "Compile-time constant binding.",
        continue: "Next loop iteration.",
        crate: "Compilation unit: root of Rust package (like a library/binary).",
        dyn: "Dynamic dispatch trait object (dyn Trait).",
        else: "Alternative branch for if/match.",
        enum: "Sum type with named variants, optionally carrying data.",
        extern: "Foreign function interface or external crate linkage.",
        fn: "Function definition keyword.",
        for: "Loop or impl trait bound syntax.",
        if: "Conditional; also used in if let pattern binding.",
        impl: "Implement methods or traits for a type.",
        let: "Bind immutable variable; mut makes it mutable.",
        loop: "Infinite loop until break.",
        match: "Exhaustive pattern matching on values.",
        mod: "Module declaration organizing code.",
        move: "Closure takes ownership of captured variables.",
        mut: "Mutable binding modifier.",
        pub: "Public visibility for items.",
        ref: "Pattern borrows by reference instead of moving.",
        return: "Exit function early with value.",
        Self: "Type alias inside impl/trait referring to implementing type.",
        self: "Method receiver: instance reference (&self, &mut self, self).",
        static: "Static lifetime or static variable.",
        struct: "Product type grouping named fields.",
        trait: "Shared behavior interface implemented by types.",
        type: "Type alias definition.",
        union: "Unsafe overlapping memory layout of fields.",
        unsafe: "Opt into operations Rust cannot verify (FFI, raw pointers).",
        use: "Import paths into scope.",
        where: "Additional constraints on generic parameters.",
        while: "Loop while condition holds.",
        yield: "Reserved; not yet stable for generators in Rust.",
      },
    },
    SQL: {
      category: "databases",
      tags: ["sql", "database"],
      words: {
        SELECT: "Retrieve columns from tables with optional filtering and joins.",
        FROM: "Specify source table(s) for a SELECT query.",
        WHERE: "Filter rows matching a boolean condition.",
        INSERT: "Add new rows into a table.",
        UPDATE: "Modify existing rows matching a condition.",
        DELETE: "Remove rows matching a condition.",
        JOIN: "Combine rows from multiple tables on related keys.",
        INNER: "Return only rows with matches in both joined tables.",
        LEFT: "Keep all left rows; NULL-fill missing right matches.",
        RIGHT: "Keep all right rows; NULL-fill missing left matches.",
        FULL: "Keep all rows from both sides with NULLs where no match.",
        ON: "Join condition specifying how tables relate.",
        GROUP: "Used with BY to aggregate rows sharing values.",
        HAVING: "Filter aggregated groups after GROUP BY.",
        ORDER: "Used with BY to sort result set.",
        LIMIT: "Cap number of rows returned.",
        OFFSET: "Skip first N rows (pagination).",
        DISTINCT: "Remove duplicate rows from result.",
        CREATE: "Define new database objects (TABLE, INDEX, VIEW).",
        ALTER: "Modify schema of existing objects.",
        DROP: "Remove database objects permanently.",
        INDEX: "Speed up queries by maintaining sorted lookup structure.",
        PRIMARY: "With KEY: uniquely identifies each row.",
        FOREIGN: "With KEY: references PRIMARY KEY in another table.",
        UNIQUE: "Constraint ensuring column values are distinct.",
        NULL: "Absence of value; comparisons use IS NULL, not =.",
        TRANSACTION: "Atomic unit of work: COMMIT or ROLLBACK together.",
        COMMIT: "Persist all changes in current transaction.",
        ROLLBACK: "Undo all changes in current transaction.",
        VIEW: "Saved query acting like a virtual table.",
        TRIGGER: "Procedure fired automatically on INSERT/UPDATE/DELETE.",
        PROCEDURE: "Stored routine executed with CALL.",
        FUNCTION: "Stored routine returning a value in SQL dialects.",
        GRANT: "Give privileges to users or roles.",
        REVOKE: "Remove previously granted privileges.",
        UNION: "Combine result sets removing duplicates (UNION ALL keeps dupes).",
        EXISTS: "Subquery test: true if subquery returns any row.",
        CASE: "Conditional expression (CASE WHEN … THEN … END).",
        CAST: "Convert value to another data type.",
        COUNT: "Aggregate: number of rows (COUNT(*) counts all).",
        SUM: "Aggregate: total of numeric column.",
        AVG: "Aggregate: arithmetic mean.",
        MIN: "Aggregate: smallest value.",
        MAX: "Aggregate: largest value.",
      },
    },
  };

  const out = [];
  for (const [lang, spec] of Object.entries(langs)) {
    for (const [word, definition] of Object.entries(spec.words)) {
      out.push({
        term: `${lang} keyword: ${word}`,
        definition,
        category: spec.category,
        tags: [...spec.tags, "keyword", lang.toLowerCase()],
        example: lang === "JavaScript" ? `// example\n${word === "const" ? "const x = 1;" : word + " …"}` : undefined,
        level: "beginner",
      });
    }
  }
  return out;
}

function algorithmsList() {
  const items = [
    ["Binary Search", "Search sorted array by halving range: O(log n) time.", "beginner"],
    ["Linear Search", "Check each element sequentially: O(n) time.", "beginner"],
    ["Bubble Sort", "Repeatedly swap adjacent out-of-order elements: O(n²).", "beginner"],
    ["Merge Sort", "Divide array, sort halves, merge: O(n log n) stable sort.", "intermediate"],
    ["Quick Sort", "Partition around pivot recursively: O(n log n) average.", "intermediate"],
    ["Heap Sort", "Build max-heap then extract: O(n log n) in-place.", "intermediate"],
    ["Insertion Sort", "Build sorted prefix by inserting each element: O(n²).", "beginner"],
    ["Selection Sort", "Repeatedly pick minimum from unsorted part: O(n²).", "beginner"],
    ["Radix Sort", "Sort integers digit-by-digit in linear time for fixed width.", "advanced"],
    ["Counting Sort", "Count occurrences when range is small: O(n + k).", "intermediate"],
    ["Bucket Sort", "Distribute into buckets then sort individually.", "intermediate"],
    ["Dijkstra's Algorithm", "Shortest paths from source in weighted graph: non-negative edges.", "advanced"],
    ["Bellman-Ford", "Shortest paths allowing negative edges; detects negative cycles.", "advanced"],
    ["Floyd-Warshall", "All-pairs shortest paths in O(V³) dynamic programming.", "advanced"],
    ["A* Search", "Heuristic graph search optimal when heuristic is admissible.", "advanced"],
    ["Breadth-First Search", "Explore graph layer by layer using a queue.", "intermediate"],
    ["Depth-First Search", "Explore graph by going deep before backtracking: stack/recursion.", "intermediate"],
    ["Topological Sort", "Linear ordering of DAG respecting edge direction.", "intermediate"],
    ["Kruskal's Algorithm", "Minimum spanning tree by adding cheapest safe edges.", "advanced"],
    ["Prim's Algorithm", "Grow MST from seed vertex picking cheapest border edge.", "advanced"],
    ["Union-Find", "Disjoint set structure for connectivity queries with path compression.", "intermediate"],
    ["KMP Algorithm", "Substring search with failure function: O(n + m).", "advanced"],
    ["Boyer-Moore", "Fast string search skipping using bad-character/good-suffix rules.", "advanced"],
    ["Levenshtein Distance", "Edit distance: min inserts/deletes/substitutions between strings.", "intermediate"],
    ["Dynamic Programming", "Solve by combining optimal sub-solutions with overlapping subproblems.", "intermediate"],
    ["Greedy Algorithm", "Make locally optimal choice hoping for global optimum.", "intermediate"],
    ["Divide and Conquer", "Split problem, solve recursively, combine results.", "intermediate"],
    ["Backtracking", "Try choices and undo when constraints fail (N-Queens, Sudoku).", "intermediate"],
    ["Monte Carlo", "Estimate results by random sampling.", "advanced"],
    ["Simulated Annealing", "Probabilistic optimization escaping local minima.", "advanced"],
    ["PageRank", "Rank web pages by random surfer model on link graph.", "advanced"],
    ["MapReduce", "Process big data with map, shuffle, reduce phases.", "advanced"],
    ["Consistent Hashing", "Distribute keys across nodes with minimal remapping on change.", "advanced"],
    ["Raft Consensus", "Leader-based replicated log for distributed agreement.", "advanced"],
    ["Paxos", "Classic consensus protocol for agreeing on a value.", "advanced"],
    ["Two-Phase Commit", "Distributed transaction commit protocol — prepare then commit.", "advanced"],
    ["Lamport Timestamp", "Logical clock ordering events in distributed systems.", "advanced"],
    ["Vector Clock", "Track causality with per-node counters.", "advanced"],
    ["Bloom Filter", "Space-efficient probabilistic set — may false-positive, never false-negative.", "intermediate"],
    ["HyperLogLog", "Approximate count of distinct elements in sublinear memory.", "advanced"],
    ["Skip List", "Probabilistic layered linked list giving O(log n) search.", "advanced"],
    ["B-Tree", "Self-balancing tree optimized for disk block reads in databases.", "advanced"],
    ["B+ Tree", "B-tree variant with linked leaves: common in database indexes.", "advanced"],
    ["Trie", "Prefix tree for strings: fast prefix lookup.", "intermediate"],
    ["Suffix Tree", "Index all suffixes of string for advanced pattern matching.", "advanced"],
    ["Segment Tree", "Range query/update structure in O(log n).", "advanced"],
    ["Fenwick Tree", "Binary indexed tree for prefix sums with updates.", "advanced"],
    ["LRU Cache", "Evict least recently used item when cache is full.", "intermediate"],
    ["LFU Cache", "Evict least frequently used cache entry.", "intermediate"],
  ];
  return items.map(([term, definition, level]) => ({
    term,
    definition,
    category: "algorithms",
    tags: ["algorithm", "computer-science"],
    level,
  }));
}

function dataStructuresList() {
  const items = [
    ["Array", "Contiguous indexed collection: O(1) random access."],
    ["Linked List", "Nodes pointing to next: O(1) insert at head, O(n) search."],
    ["Doubly Linked List", "Nodes with next and prev pointers for bidirectional traversal."],
    ["Stack", "LIFO structure: push/pop at top (call stack, undo)."],
    ["Queue", "FIFO structure: enqueue rear, dequeue front."],
    ["Deque", "Double-ended queue: insert/remove both ends."],
    ["Priority Queue", "Elements dequeued by priority (heap-backed typically)."],
    ["Binary Heap", "Complete binary tree with heap property for min/max."],
    ["Hash Table", "Key-value map with average O(1) lookup via hash function."],
    ["Hash Map", "Associative array implemented with hashing and collision resolution."],
    ["Hash Set", "Collection of unique keys without associated values."],
    ["Tree", "Hierarchical nodes with parent-child relationships."],
    ["Binary Tree", "Tree where each node has at most two children."],
    ["Binary Search Tree", "Ordered binary tree: left < root < right."],
    ["AVL Tree", "Self-balancing BST with height difference ≤ 1."],
    ["Red-Black Tree", "Self-balancing BST with color invariants: used in stdlib maps."],
    ["Graph", "Vertices connected by edges: directed or undirected."],
    ["Adjacency Matrix", "V×V matrix marking edges between graph vertices."],
    ["Adjacency List", "Array of lists: space-efficient for sparse graphs."],
    ["Set", "Collection of unique elements with membership tests."],
    ["Multiset", "Set allowing duplicate counts (bag)."],
    ["Map", "Associative container mapping keys to values."],
    ["Record", "Fixed set of named fields (struct/product type)."],
    ["Tuple", "Fixed-size ordered sequence: often heterogeneous types."],
    ["Optional", "Type that may or may not contain a value (Maybe)."],
    ["Result Type", "Success or error value without throwing exceptions."],
    ["Ring Buffer", "Fixed-size circular queue for streaming I/O."],
    ["Circular Buffer", "Same as ring buffer: overwrite oldest when full."],
  ];
  return items.map(([term, definition]) => ({
    term,
    definition,
    category: "algorithms",
    tags: ["data-structure"],
    level: "intermediate",
  }));
}

function designPatterns() {
  const patterns = [
    ["Singleton", "Ensure class has only one instance with global access point.", "architecture"],
    ["Factory Method", "Interface for creating objects; subclasses decide concrete type.", "architecture"],
    ["Abstract Factory", "Create families of related objects without specifying classes.", "architecture"],
    ["Builder", "Construct complex object step by step separating representation.", "architecture"],
    ["Prototype", "Clone existing instance instead of creating from scratch.", "architecture"],
    ["Adapter", "Convert interface of class into another clients expect.", "architecture"],
    ["Bridge", "Split abstraction and implementation into separate hierarchies.", "architecture"],
    ["Composite", "Tree structure treating individual and groups uniformly.", "architecture"],
    ["Decorator", "Attach responsibilities dynamically wrapping object.", "architecture"],
    ["Facade", "Simplified interface to complex subsystem.", "architecture"],
    ["Flyweight", "Share intrinsic state among many fine-grained objects.", "architecture"],
    ["Proxy", "Surrogate controlling access to another object.", "architecture"],
    ["Chain of Responsibility", "Pass request along handler chain until one handles it.", "architecture"],
    ["Command", "Encapsulate request as object: undo, queue, log.", "architecture"],
    ["Iterator", "Sequential access to aggregate without exposing internals.", "architecture"],
    ["Mediator", "Central object coordinating colleagues reducing coupling.", "architecture"],
    ["Memento", "Capture and restore object internal state.", "architecture"],
    ["Observer", "One-to-many notify on state change (pub/sub).", "architecture"],
    ["State", "Object behavior changes when internal state changes.", "architecture"],
    ["Strategy", "Family of algorithms interchangeable at runtime.", "architecture"],
    ["Template Method", "Skeleton algorithm with subclass-overridable steps.", "architecture"],
    ["Visitor", "Separate algorithm from object structure it operates on.", "architecture"],
    ["Repository Pattern", "Abstraction over data access hiding persistence details.", "architecture"],
    ["Unit of Work", "Track changes and commit as single transaction.", "architecture"],
    ["CQRS", "Separate read and write models for scalability.", "architecture"],
    ["Event Sourcing", "Store state changes as sequence of events.", "architecture"],
    ["Saga Pattern", "Manage distributed transactions as sequence of local steps.", "architecture"],
    ["Circuit Breaker", "Stop calling failing service to allow recovery.", "architecture"],
    ["Bulkhead", "Isolate resources so failure in one pool doesn't sink all.", "architecture"],
    ["Sidecar Pattern", "Helper container alongside main app pod (service mesh).", "architecture"],
  ];
  return patterns.map(([term, definition, category]) => ({
    term: term.includes("Pattern") ? term : `${term} Pattern`,
    definition,
    category,
    tags: ["design-pattern", "architecture"],
    level: "advanced",
  }));
}

function acronyms() {
  const list = {
    API: "Application Programming Interface: contract for software components to communicate.",
    REST: "Representational State Transfer: architectural style using HTTP verbs on resources.",
    CRUD: "Create, Read, Update, Delete: basic persistence operations.",
    JSON: "JavaScript Object Notation: text format for structured data.",
    XML: "Extensible Markup Language: tagged hierarchical documents.",
    YAML: "YAML Ain't Markup Language: human-readable config/data serialization.",
    HTML: "HyperText Markup Language: structure of web documents.",
    CSS: "Cascading Style Sheets: presentation rules for HTML.",
    DOM: "Document Object Model: tree API representing HTML/XML in memory.",
    AJAX: "Asynchronous JavaScript and XML: update pages without full reload.",
    SPA: "Single Page Application: one HTML page with client-side routing.",
    SSR: "Server-Side Rendering: HTML generated on server per request.",
    SSG: "Static Site Generation: HTML built at compile/deploy time.",
    ISR: "Incremental Static Regeneration: update static pages after deploy.",
    CDN: "Content Delivery Network: geographically distributed cache edge servers.",
    DNS: "Domain Name System: maps hostnames to IP addresses.",
    TCP: "Transmission Control Protocol: reliable ordered byte stream.",
    UDP: "User Datagram Protocol: connectionless fast datagrams without guarantees.",
    IP: "Internet Protocol: routing packets across networks (IPv4/IPv6).",
    TLS: "Transport Layer Security: encrypts traffic (successor to SSL).",
    SSL: "Secure Sockets Layer: deprecated predecessor of TLS.",
    HTTPS: "HTTP over TLS: encrypted web protocol.",
    SSH: "Secure Shell: encrypted remote login and tunneling.",
    FTP: "File Transfer Protocol: legacy file transfer (use SFTP/FTPS).",
    SFTP: "SSH File Transfer Protocol: secure file operations over SSH.",
    SMTP: "Simple Mail Transfer Protocol: sending email.",
    IMAP: "Internet Message Access Protocol: sync mail folders on server.",
    POP3: "Post Office Protocol v3: download mail to client.",
    OAuth: "Open Authorization: delegated access without sharing password.",
    OIDC: "OpenID Connect: identity layer on top of OAuth 2.0.",
    JWT: "JSON Web Token: signed claims for stateless auth.",
    SAML: "Security Assertion Markup Language: enterprise SSO XML standard.",
    CORS: "Cross-Origin Resource Sharing: browser policy for cross-domain requests.",
    CSRF: "Cross-Site Request Forgery: trick browser into unwanted authenticated action.",
    XSS: "Cross-Site Scripting: inject malicious scripts into pages others view.",
    SQLi: "SQL Injection: attacker manipulates queries via unsanitized input.",
    ORM: "Object-Relational Mapping: map tables to objects in code.",
    MVC: "Model-View-Controller: separates data, UI, and control logic.",
    MVVM: "Model-View-ViewModel: data binding between view and model.",
    MVP: "Model-View-Presenter: presenter mediates view and model.",
    CI: "Continuous Integration: automatically build/test on each change.",
    CD: "Continuous Delivery/Deployment: automate release to production.",
    IaC: "Infrastructure as Code: define servers/networks in versioned files.",
    GUI: "Graphical User Interface: windows, buttons, visual interaction.",
    CLI: "Command Line Interface: text commands in terminal.",
    TUI: "Text User Interface: terminal UI with panels and menus.",
    IDE: "Integrated Development Environment: editor plus debugger/build tools.",
    SDK: "Software Development Kit: libraries and tools for a platform.",
    LLVM: "Low Level Virtual Machine: compiler infrastructure (IR, optimizations).",
    JIT: "Just-In-Time compilation: compile bytecode to machine code at runtime.",
    AOT: "Ahead-Of-Time compilation: compile before execution.",
    GC: "Garbage Collection: automatic reclaim of unreachable memory.",
    RAII: "Resource Acquisition Is Initialization: C++ scope-bound cleanup.",
    OOP: "Object-Oriented Programming: objects with data and behavior.",
    FP: "Functional Programming: functions as first-class, immutability emphasis.",
    DSL: "Domain-Specific Language: tailored syntax for one problem domain.",
    GPL: "General Purpose Language: usable for many kinds of programs.",
    AST: "Abstract Syntax Tree: parsed code structure without syntax noise.",
    IR: "Intermediate Representation: compiler internal form between source and machine code.",
    CPU: "Central Processing Unit: executes instructions.",
    GPU: "Graphics Processing Unit: parallel SIMD for graphics and ML.",
    RAM: "Random Access Memory: volatile working memory.",
    ROM: "Read-Only Memory: non-volatile firmware storage.",
    SSD: "Solid State Drive: flash storage without spinning disks.",
    HDD: "Hard Disk Drive: magnetic spinning storage.",
    BIOS: "Basic Input/Output System: firmware initializing hardware at boot.",
    UEFI: "Unified Extensible Firmware Interface: modern BIOS replacement.",
    VM: "Virtual Machine: emulated computer on host hardware.",
    KVM: "Kernel-based Virtual Machine: Linux hardware virtualization.",
    NLP: "Natural Language Processing: computers understanding human language.",
    LLM: "Large Language Model: neural network trained on vast text.",
    ML: "Machine Learning: learn patterns from data without explicit rules.",
    DL: "Deep Learning: neural networks with many layers.",
    CNN: "Convolutional Neural Network: image/spatial pattern recognition.",
    RNN: "Recurrent Neural Network: sequence modeling with memory (legacy).",
    LSTM: "Long Short-Term Memory: RNN variant handling long dependencies.",
    GAN: "Generative Adversarial Network: generator vs discriminator training.",
    PCA: "Principal Component Analysis: dimensionality reduction technique.",
    ETL: "Extract, Transform, Load: data pipeline into warehouse.",
    OLAP: "Online Analytical Processing: multidimensional analytics queries.",
    OLTP: "Online Transaction Processing: short transactional reads/writes.",
    CAP: "Consistency, Availability, Partition tolerance: pick two in distributed DB.",
    PACELC: "Extension of CAP: latency vs consistency when no partition.",
    BASE: "Basically Available, Soft state, Eventual consistency: NoSQL philosophy.",
    ACID: "Atomicity, Consistency, Isolation, Durability: transactional guarantees.",
    UUID: "Universally Unique Identifier: 128-bit identifier (v4 random common).",
    GUID: "Globally Unique Identifier: Microsoft term for UUID.",
    URI: "Uniform Resource Identifier: string identifying resource (URL or URN).",
    URL: "Uniform Resource Locator: location of resource on network.",
    URN: "Uniform Resource Name: persistent name without location.",
    IPC: "Inter-Process Communication: processes exchanging data.",
    RPC: "Remote Procedure Call: invoke function on another machine.",
    gRPC: "Google RPC: HTTP/2 protobuf-based high performance RPC.",
    SOAP: "Simple Object Access Protocol: XML-based web services (legacy).",
    WSDL: "Web Services Description Language: XML API contract for SOAP.",
    GraphQL: "Query language letting clients request exact fields needed.",
    WASM: "WebAssembly: portable binary instruction format for browsers.",
    PWA: "Progressive Web App: web app with offline/install capabilities.",
    SEO: "Search Engine Optimization: improve discoverability in search results.",
    KPI: "Key Performance Indicator: measurable business/engineering metric.",
    SLA: "Service Level Agreement: uptime/latency commitments.",
    SLO: "Service Level Objective: internal target backing SLA.",
    SLI: "Service Level Indicator: measured metric (latency, error rate).",
    MTTR: "Mean Time To Recovery: average time to restore service.",
    MTBF: "Mean Time Between Failures: reliability metric.",
    RPO: "Recovery Point Objective: max acceptable data loss window.",
    RTO: "Recovery Time Objective: max acceptable downtime.",
    POC: "Proof of Concept: small demo validating feasibility.",
    MVP: "Minimum Viable Product: smallest product delivering core value.",
    TDD: "Test-Driven Development: write failing test before implementation.",
    BDD: "Behavior-Driven Development: tests described in natural language.",
    DDD: "Domain-Driven Design: model software around business domain.",
    SOLID: "Five OOP principles: Single responsibility, Open-closed, Liskov, Interface segregation, Dependency inversion.",
    DRY: "Don't Repeat Yourself: avoid duplicating logic.",
    KISS: "Keep It Simple, Stupid: prefer simple solutions.",
    YAGNI: "You Aren't Gonna Need It: don't build unused features.",
    FOMO: "Fear Of Missing Out: not technical but appears in tech culture.",
    RFC: "Request For Comments: IETF standards documents (HTTP, TCP, etc.).",
    IETF: "Internet Engineering Task Force: develops Internet standards.",
    W3C: "World Wide Web Consortium: web standards (HTML, CSS).",
    WHATWG: "Web Hypertext Application Technology Working Group: HTML living standard.",
    ECMA: "European standards body publishing ECMAScript (JavaScript spec).",
    ISO: "International Organization for Standardization: global standards.",
    ANSI: "American National Standards Institute: US standards coordination.",
    POSIX: "Portable Operating System Interface: Unix-like API standard.",
    UTF: "Unicode Transformation Format: encodes Unicode code points (UTF-8 common).",
    ASCII: "American Standard Code: 7-bit character encoding (0–127).",
    BOM: "Byte Order Mark: Unicode marker at file start (UTF-8 BOM optional).",
    EOF: "End Of File: marker or condition when no more data to read.",
    CRUD: "Create Read Update Delete: basic data operations.",
    IoC: "Inversion of Control: framework calls your code (not vice versa).",
    DI: "Dependency Injection: supply dependencies from outside class.",
    AOP: "Aspect-Oriented Programming: cross-cutting concerns as aspects.",
    ESB: "Enterprise Service Bus: integrate apps via message routing.",
    EAI: "Enterprise Application Integration: connect disparate business systems.",
    ERP: "Enterprise Resource Planning: integrated business management software.",
    CRM: "Customer Relationship Management: sales/support customer data.",
    CMS: "Content Management System: publish web content without coding.",
    LMS: "Learning Management System: deliver online courses.",
    SaaS: "Software as a Service: hosted subscription software.",
    PaaS: "Platform as a Service: deploy apps without managing servers.",
    IaaS: "Infrastructure as a Service: rent VMs, storage, networks.",
    FaaS: "Function as a Service: serverless event-driven functions.",
    BaaS: "Backend as a Service: mobile/web backend APIs hosted.",
    NFR: "Non-Functional Requirement: performance, security, scalability.",
    POC: "Proof of Concept: validate idea quickly.",
  };
  return Object.entries(list).map(([term, definition]) => ({
    term,
    definition,
    category: "fundamentals",
    tags: ["acronym", "fundamentals"],
    level: "beginner",
  }));
}

function cloudServices() {
  const services = [
    ["AWS EC2", "Elastic Compute Cloud: virtual servers in Amazon cloud.", "devops"],
    ["AWS S3", "Simple Storage Service: object storage with high durability.", "devops"],
    ["AWS Lambda", "Run code on demand without managing servers.", "devops"],
    ["AWS RDS", "Managed relational databases (MySQL, Postgres, etc.).", "devops"],
    ["AWS VPC", "Virtual Private Cloud: isolated network in AWS.", "devops"],
    ["AWS IAM", "Identity and Access Management: users, roles, policies.", "security"],
    ["AWS CloudFront", "CDN distributing content from edge locations.", "devops"],
    ["AWS Route 53", "DNS and domain routing service.", "networking"],
    ["AWS ECS", "Elastic Container Service: run Docker containers.", "devops"],
    ["AWS EKS", "Managed Kubernetes on AWS.", "devops"],
    ["AWS SQS", "Simple Queue Service: managed message queue.", "devops"],
    ["AWS SNS", "Simple Notification Service: pub/sub messaging.", "devops"],
    ["AWS DynamoDB", "Managed NoSQL key-value/document database.", "databases"],
    ["AWS CloudWatch", "Monitoring metrics, logs, and alarms.", "devops"],
    ["Azure VMs", "Virtual machines on Microsoft Azure cloud.", "devops"],
    ["Azure Blob Storage", "Object storage for unstructured data.", "devops"],
    ["Azure Functions", "Serverless compute on Azure.", "devops"],
    ["Azure AD", "Azure Active Directory: identity and SSO.", "security"],
    ["Google Cloud Run", "Fully managed containers from container image.", "devops"],
    ["Google BigQuery", "Serverless data warehouse for analytics.", "databases"],
    ["Google Kubernetes Engine", "Managed Kubernetes (GKE).", "devops"],
    ["Terraform", "HashiCorp IaC tool using HCL to provision cloud resources.", "devops"],
    ["Ansible", "Agentless configuration management using YAML playbooks.", "devops"],
    ["Puppet", "Declarative configuration management with agent on nodes.", "devops"],
    ["Chef", "Infrastructure automation using Ruby-based recipes.", "devops"],
    ["Pulumi", "IaC using general-purpose languages (TypeScript, Python).", "devops"],
    ["CloudFormation", "AWS-native IaC using YAML/JSON templates.", "devops"],
    ["Helm", "Package manager for Kubernetes charts.", "devops"],
    ["Kubernetes", "Orchestrates container deployment, scaling, and networking.", "devops"],
    ["Docker", "Packages app and dependencies into portable containers.", "devops"],
    ["Podman", "Daemonless container engine compatible with Docker CLI.", "devops"],
    ["containerd", "Industry-standard container runtime beneath Docker/K8s.", "devops"],
    ["CNI", "Container Network Interface: plugins for pod networking.", "networking"],
    ["CSI", "Container Storage Interface: volume plugins for containers.", "devops"],
    ["Ingress", "Kubernetes HTTP routing into cluster services.", "devops"],
    ["Service Mesh", "Sidecar proxies managing service-to-service traffic (Istio, Linkerd).", "devops"],
    ["Istio", "Popular Kubernetes service mesh for traffic, security, observability.", "devops"],
    ["Prometheus", "Time-series metrics collection and alerting.", "devops"],
    ["Grafana", "Dashboards visualizing metrics from Prometheus and others.", "devops"],
    ["ELK Stack", "Elasticsearch, Logstash, Kibana: log aggregation pipeline.", "devops"],
    ["Fluentd", "Unified logging layer collecting and forwarding logs.", "devops"],
    ["Jaeger", "Distributed tracing for microservices.", "devops"],
    ["OpenTelemetry", "Vendor-neutral observability APIs for traces, metrics, logs.", "devops"],
  ];
  return services.map(([term, definition, category]) => ({
    term,
    definition,
    category,
    tags: ["cloud", "devops"],
    level: "intermediate",
  }));
}

function webTerms() {
  const terms = [
    ["WebSocket", "Full-duplex TCP connection for real-time browser-server messaging.", "web"],
    ["Server-Sent Events", "One-way stream of events from server to browser over HTTP.", "web"],
    ["Service Worker", "Background script enabling offline caching and push notifications.", "web"],
    ["WebRTC", "Peer-to-peer audio/video and data in browsers.", "web"],
    ["IndexedDB", "Browser embedded object database for large client-side storage.", "web"],
    ["localStorage", "Key-value storage persisted per origin (synchronous, ~5MB).", "web"],
    ["sessionStorage", "Like localStorage but cleared when tab closes.", "web"],
    ["Cookie", "Small key-value sent with HTTP requests; used for sessions.", "web"],
    ["Same-Origin Policy", "Browser restricts cross-origin DOM and data access.", "web"],
    ["Content Security Policy", "HTTP header restricting script/style/load sources.", "security"],
    ["Subresource Integrity", "Hash verify CDN scripts haven't been tampered.", "security"],
    ["Virtual DOM", "In-memory DOM diffed before updating real DOM (React).", "web"],
    ["Shadow DOM", "Encapsulated DOM subtree hidden from global CSS.", "web"],
    ["Custom Element", "Web Components API defining reusable HTML tags.", "web"],
    ["Hydration", "Attach event listeners to server-rendered HTML on client.", "web"],
    ["Tree Shaking", "Remove unused exports during bundling.", "tools"],
    ["Code Splitting", "Load JavaScript chunks on demand reducing initial bundle.", "web"],
    ["Lazy Loading", "Defer loading resources until needed.", "web"],
    ["Prefetch", "Hint browser to fetch resources likely needed soon.", "web"],
    ["Preload", "High-priority fetch of critical resource early.", "web"],
    ["Critical CSS", "Minimal CSS inlined for above-the-fold first paint.", "web"],
    ["Core Web Vitals", "Google metrics: LCP, INP, CLS for user experience.", "web"],
    ["Largest Contentful Paint", "Time until largest visible content renders.", "web"],
    ["Cumulative Layout Shift", "Visual stability: unexpected layout movement.", "web"],
    ["Interaction to Next Paint", "Responsiveness metric replacing FID.", "web"],
    ["Semantic HTML", "Use meaningful tags (nav, article) for accessibility/SEO.", "web"],
    ["ARIA", "Accessible Rich Internet Applications: roles/states for assistive tech.", "web"],
    ["WCAG", "Web Content Accessibility Guidelines: a11y standard levels A/AA/AAA.", "web"],
    ["Responsive Design", "Layout adapts to viewport using fluid grids and media queries.", "web"],
    ["Mobile First", "Design for small screens first then enhance for desktop.", "web"],
    ["Flexbox", "CSS one-dimensional layout distributing space along axis.", "web"],
    ["CSS Grid", "CSS two-dimensional grid layout for rows and columns.", "web"],
    ["BEM", "Block Element Modifier: CSS naming convention avoiding specificity wars.", "web"],
    ["Sass", "CSS preprocessor with variables, nesting, mixins.", "web"],
    ["PostCSS", "Transform CSS with plugins (autoprefixer, tailwind).", "web"],
    ["Tailwind CSS", "Utility-first CSS framework composing classes in markup.", "web"],
    ["Bootstrap", "Popular CSS component framework with grid system.", "web"],
    ["React", "UI library using components and declarative state-driven rendering.", "web"],
    ["Vue.js", "Progressive framework for building user interfaces.", "web"],
    ["Angular", "Full TypeScript framework with DI, routing, and templates.", "web"],
    ["Svelte", "Compile-time framework — no virtual DOM runtime.", "web"],
    ["Next.js", "React framework with SSR, SSG, and file-based routing.", "web"],
    ["Nuxt", "Vue meta-framework for SSR and static sites.", "web"],
    ["Remix", "Full-stack React framework focused on web standards.", "web"],
    ["Vite", "Fast dev server and bundler using native ES modules.", "tools"],
    ["Webpack", "Module bundler packing JS/CSS/assets for production.", "tools"],
    ["Rollup", "ES module bundler optimizing tree-shaking.", "tools"],
    ["esbuild", "Extremely fast JS bundler written in Go.", "tools"],
    ["Babel", "Transpile modern JavaScript to older syntax for compatibility.", "tools"],
    ["TypeScript", "Typed superset of JavaScript compiling to plain JS.", "languages"],
    ["JSX", "Syntax extension embedding HTML-like markup in JavaScript.", "web"],
    ["npm", "Node package manager — registry and CLI for JavaScript packages.", "tools"],
    ["yarn", "Alternative package manager with lockfile and workspaces.", "tools"],
    ["pnpm", "Package manager using content-addressable store saving disk.", "tools"],
    ["Express.js", "Minimal Node.js web framework for APIs and servers.", "web"],
    ["Fastify", "High-performance Node.js web framework with schema validation.", "web"],
    ["Django", "Python full-stack web framework with ORM and admin.", "web"],
    ["Flask", "Lightweight Python micro web framework.", "web"],
    ["Rails", "Ruby full-stack framework emphasizing convention over configuration.", "web"],
    ["Laravel", "PHP web framework with elegant syntax and Eloquent ORM.", "web"],
    ["Spring Boot", "Java framework for production-ready microservices.", "web"],
    ["ASP.NET Core", "Cross-platform web framework from Microsoft.", "web"],
  ];
  return terms.map(([term, definition, category]) => ({
    term,
    definition,
    category,
    tags: ["web"],
    level: "intermediate",
  }));
}

function securityTerms() {
  const terms = [
    ["Encryption", "Transform data so only authorized parties can read it.", "security"],
    ["Symmetric Encryption", "Same key encrypts and decrypts (AES, ChaCha20).", "security"],
    ["Asymmetric Encryption", "Public key encrypts; private key decrypts (RSA, ECC).", "security"],
    ["Hash Function", "One-way digest producing fixed-size fingerprint (SHA-256).", "security"],
    ["Salt", "Random value added before hashing passwords defeating rainbow tables.", "security"],
    ["Pepper", "Secret added to password hash stored outside database.", "security"],
    ["bcrypt", "Adaptive password hashing function with cost factor.", "security"],
    ["Argon2", "Modern memory-hard password hashing winner of PHC.", "security"],
    ["HMAC", "Hash-based Message Authentication Code verifying integrity.", "security"],
    ["Digital Signature", "Prove message authenticity using private key.", "security"],
    ["Certificate Authority", "Trusted entity issuing TLS certificates.", "security"],
    ["Public Key Infrastructure", "System managing digital certificates and trust chains.", "security"],
    ["Man-in-the-Middle Attack", "Attacker intercepts communication between two parties.", "security"],
    ["Phishing", "Social engineering tricking users into revealing credentials.", "security"],
    ["Zero Day", "Vulnerability unknown to vendor with no patch yet.", "security"],
    ["CVE", "Common Vulnerabilities and Exposures: public vulnerability ID.", "security"],
    ["CVSS", "Common Vulnerability Scoring System: severity score 0–10.", "security"],
    ["Penetration Testing", "Authorized simulated attack finding security weaknesses.", "security"],
    ["Red Team", "Offensive security team simulating real attackers.", "security"],
    ["Blue Team", "Defensive security monitoring and incident response.", "security"],
    ["SOC", "Security Operations Center: 24/7 monitoring and response.", "security"],
    ["SIEM", "Security Information and Event Management: aggregate and correlate logs.", "security"],
    ["WAF", "Web Application Firewall filtering HTTP traffic.", "security"],
    ["DDoS", "Distributed Denial of Service: overwhelm service with traffic.", "security"],
    ["Rate Limiting", "Restrict request frequency preventing abuse.", "security"],
    ["Principle of Least Privilege", "Grant minimum permissions needed for task.", "security"],
    ["Defense in Depth", "Multiple layered security controls.", "security"],
    ["Threat Model", "Structured analysis of assets, threats, and mitigations.", "security"],
    ["STRIDE", "Threat categories: Spoofing, Tampering, Repudiation, Info disclosure, DoS, Elevation.", "security"],
    ["OWASP Top 10", "Most critical web application security risks list.", "security"],
    ["Secrets Management", "Secure storage and rotation of API keys and passwords.", "security"],
    ["Vault", "HashiCorp tool for secrets, encryption as a service.", "security"],
    ["mTLS", "Mutual TLS: both client and server present certificates.", "security"],
    ["Zero Trust", "Never trust, always verify: no implicit network trust.", "security"],
  ];
  return terms.map(([term, definition, category]) => ({
    term,
    definition,
    category,
    tags: ["security"],
    level: "intermediate",
  }));
}

function generateAll() {
  const entries = [];
  addEntries(entries, httpStatusCodes());
  addEntries(entries, wellKnownPorts());
  addEntries(entries, mimeTypes());
  addEntries(entries, languageKeywords());
  addEntries(entries, algorithmsList());
  addEntries(entries, dataStructuresList());
  addEntries(entries, designPatterns());
  addEntries(entries, acronyms());
  addEntries(entries, cloudServices());
  addEntries(entries, webTerms());
  addEntries(entries, securityTerms());
  return entries;
}

module.exports = {
  CATEGORIES,
  slugify,
  generateAll,
};