const CATALOG = [
  {
    id: "myspace-browser",
    name: "My Space Browser",
    category: "browser",
    categoryLabel: "Browser",
    description: "Search apps, Connect, and My Space content, then browse the web",
    color: "#3DDC97",
    openUrl: "myspace://browser/home",
    kind: "web",
    howto: "Search on the home page or in the address bar. Open apps, Connect services, or any website.",
    fields: [],
    logo: "myspace-browser",
  },
  {
    id: "google",
    name: "Google",
    category: "browser",
    categoryLabel: "Browser",
    description: "Full browser: starts at Google Search",
    color: "#4285F4",
    openUrl: "https://www.google.com",
    kind: "web",
    howto: "Browse with the address bar at the top. Sign in inside My Space if needed.",
    fields: [],
    logo: "google",
  },
  {
    id: "edge",
    name: "Microsoft Edge",
    category: "browser",
    categoryLabel: "Browser",
    description: "Full browser: starts at Bing (Microsoft)",
    color: "#0078D4",
    openUrl: "https://www.bing.com",
    kind: "web",
    howto: "Use the address bar at the top to visit any site. Bing is the Microsoft start page.",
    fields: [],
    logo: "edge",
  },
  {
    id: "browser",
    name: "Browser",
    category: "browser",
    categoryLabel: "Browser",
    description: "Generic browser tab: type any address",
    color: "#1a73e8",
    openUrl: "https://www.google.com/webhp",
    kind: "web",
    howto: "Type a URL in the address bar above the page.",
    fields: [],
    logo: "browser",
  },

  {
    id: "gmail",
    name: "Gmail",
    category: "mail",
    categoryLabel: "Mail",
    description: "Gmail web inbox inside My Space",
    color: "#EA4335",
    openUrl: "https://mail.google.com/mail/",
    kind: "web",
    howto: "Sign in inside the My Space tab.",
    fields: [],
    logo: "gmail",
  },
  {
    id: "outlook",
    name: "Outlook",
    category: "mail",
    categoryLabel: "Mail",
    description: "Outlook web inbox",
    color: "#0078D4",
    openUrl: "https://outlook.live.com/mail/",
    kind: "web",
    howto: "Sign in with your Microsoft account.",
    fields: [],
    logo: "outlook",
  },
  {
    id: "yahoo",
    name: "Yahoo Mail",
    category: "mail",
    categoryLabel: "Mail",
    description: "Yahoo web inbox",
    color: "#6001D2",
    openUrl: "https://mail.yahoo.com",
    kind: "web",
    howto: "Sign in with your Yahoo account.",
    fields: [],
    logo: "yahoo",
  },

  {
    id: "whatsapp",
    name: "WhatsApp",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "WhatsApp Web: scan QR with your phone",
    color: "#25D366",
    openUrl: "https://web.whatsapp.com",
    kind: "web",
    howto: "Phone → WhatsApp → Linked devices → Link a device → scan the QR.",
    fields: [],
    logo: "whatsapp",
  },
  {
    id: "telegram",
    name: "Telegram",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "Telegram Web",
    color: "#229ED9",
    openUrl: "https://web.telegram.org/k/",
    kind: "web",
    howto: "Sign in with your phone number.",
    fields: [],
    logo: "telegram",
  },
  {
    id: "discord",
    name: "Discord",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "Discord app",
    color: "#5865F2",
    openUrl: "https://discord.com/app",
    kind: "web",
    howto: "Sign in with Discord.",
    fields: [],
    logo: "discord",
  },
  {
    id: "slack",
    name: "Slack",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "Slack workspace",
    color: "#611F69",
    openUrl: "https://app.slack.com",
    kind: "web",
    howto: "Sign in to your workspace.",
    fields: [],
    logo: "slack",
  },
  {
    id: "messenger",
    name: "Messenger",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "Facebook Messenger",
    color: "#0084FF",
    openUrl: "https://www.messenger.com",
    kind: "web",
    howto: "Sign in with Facebook.",
    fields: [],
    logo: "messenger",
  },
  {
    id: "teams",
    name: "Teams",
    category: "messaging",
    categoryLabel: "Messaging",
    description: "Microsoft Teams",
    color: "#6264A7",
    openUrl: "https://teams.microsoft.com",
    kind: "web",
    howto: "Sign in with Microsoft work/school account.",
    fields: [],
    logo: "teams",
  },

  {
    id: "facebook",
    name: "Facebook",
    category: "social",
    categoryLabel: "Social",
    description: "Facebook",
    color: "#1877F2",
    openUrl: "https://www.facebook.com",
    kind: "web",
    howto: "Sign in with Facebook.",
    fields: [],
    logo: "facebook",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "social",
    categoryLabel: "Social",
    description: "Instagram",
    color: "#E4405F",
    openUrl: "https://www.instagram.com",
    kind: "web",
    howto: "Sign in with Instagram.",
    fields: [],
    logo: "instagram",
  },
  {
    id: "x",
    name: "X",
    category: "social",
    categoryLabel: "Social",
    description: "X (Twitter)",
    color: "#111111",
    openUrl: "https://x.com",
    kind: "web",
    howto: "Sign in with X.",
    fields: [],
    logo: "x",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "social",
    categoryLabel: "Social",
    description: "LinkedIn",
    color: "#0A66C2",
    openUrl: "https://www.linkedin.com",
    kind: "web",
    howto: "Sign in with LinkedIn.",
    fields: [],
    logo: "linkedin",
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "social",
    categoryLabel: "Social",
    description: "Reddit",
    color: "#FF4500",
    openUrl: "https://www.reddit.com",
    kind: "web",
    howto: "Browse or sign in to Reddit.",
    fields: [],
    logo: "reddit",
  },
  {
    id: "tiktok",
    name: "TikTok",
    category: "social",
    categoryLabel: "Social",
    description: "TikTok",
    color: "#010101",
    openUrl: "https://www.tiktok.com",
    kind: "web",
    howto: "Sign in or browse TikTok.",
    fields: [],
    logo: "tiktok",
  },

  {
    id: "ollama",
    name: "Ollama",
    category: "ai",
    categoryLabel: "AI",
    description: "Local Ollama (localhost:11434)",
    color: "#111111",
    openUrl: "http://127.0.0.1:11434",
    kind: "web",
    howto: "Requires Ollama running on this PC. For a chat UI, open Open WebUI (often http://127.0.0.1:8080) separately if you use it.",
    fields: [],
    logo: "ollama",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "ai",
    categoryLabel: "AI",
    description: "ChatGPT",
    color: "#10A37F",
    openUrl: "https://chatgpt.com",
    kind: "web",
    howto: "Sign in with OpenAI / ChatGPT account.",
    fields: [],
    logo: "chatgpt",
  },
  {
    id: "claude",
    name: "Claude",
    category: "ai",
    categoryLabel: "AI",
    description: "Claude by Anthropic",
    color: "#D97757",
    openUrl: "https://claude.ai",
    kind: "web",
    howto: "Sign in with Anthropic account.",
    fields: [],
    logo: "claude",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "ai",
    categoryLabel: "AI",
    description: "Google Gemini inside My Space",
    color: "#8E75B2",
    openUrl: "https://gemini.google.com",
    kind: "web",
    howto: "Sign in inside the My Space tab.",
    fields: [],
    logo: "gemini",
  },

  {
    id: "youtube",
    name: "YouTube",
    category: "media",
    categoryLabel: "Media",
    description: "YouTube inside My Space",
    color: "#FF0000",
    openUrl: "https://www.youtube.com",
    kind: "web",
    howto: "Sign in inside the My Space tab if needed.",
    fields: [],
    logo: "youtube",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "media",
    categoryLabel: "Media",
    description: "Spotify Web Player",
    color: "#1DB954",
    openUrl: "https://open.spotify.com",
    kind: "web",
    howto: "Sign in with Spotify.",
    fields: [],
    logo: "spotify",
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "media",
    categoryLabel: "Media",
    description: "Netflix",
    color: "#E50914",
    openUrl: "https://www.netflix.com",
    kind: "web",
    howto: "Sign in with Netflix.",
    fields: [],
    logo: "netflix",
  },

  {
    id: "github",
    name: "GitHub",
    category: "tools",
    categoryLabel: "Tools",
    description: "GitHub",
    color: "#24292F",
    openUrl: "https://github.com",
    kind: "web",
    howto: "Sign in with GitHub.",
    fields: [],
    logo: "github",
  },
  {
    id: "notion",
    name: "Notion",
    category: "tools",
    categoryLabel: "Tools",
    description: "Notion",
    color: "#000000",
    openUrl: "https://www.notion.so",
    kind: "web",
    howto: "Sign in with Notion.",
    fields: [],
    logo: "notion",
  },
  {
    id: "drive",
    name: "Google Drive",
    category: "tools",
    categoryLabel: "Tools",
    description: "Google Drive inside My Space",
    color: "#1FA463",
    openUrl: "https://drive.google.com",
    kind: "web",
    howto: "Sign in inside the My Space tab.",
    fields: [],
    logo: "drive",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    category: "tools",
    categoryLabel: "Tools",
    description: "Microsoft OneDrive",
    color: "#0078D4",
    openUrl: "https://onedrive.live.com",
    kind: "web",
    howto: "Sign in with Microsoft.",
    fields: [],
    logo: "onedrive",
  },
];

function publicCatalog() {
  return CATALOG.map((s) => ({
    id: s.id,
    name: s.name,
    category: s.category,
    categoryLabel: s.categoryLabel,
    description: s.description,
    color: s.color,
    openUrl: s.openUrl,
    openIn: s.openIn || "embed",
    kind: s.kind || (s.builtin ? "builtin" : "web"),
    howto: s.howto || "",
    openMode: s.openMode || "shell",
    builtin: s.builtin || null,
    fields: (s.fields || []).map((f) => ({
      key: f.key,
      label: f.label,
      type: f.type || "text",
      required: f.required === true,
      placeholder: f.placeholder || "",
      secret: f.secret === true,
    })),
    logo: s.logo,
  }));
}

function getService(id) {
  return CATALOG.find((s) => s.id === String(id || "")) || null;
}

module.exports = { CATALOG, publicCatalog, getService };