const LANGUAGES = [
  { code: "auto", name: "Detect language", native: "Auto" },
  { code: "af", name: "Afrikaans", native: "Afrikaans" },
  { code: "sq", name: "Albanian", native: "Shqip" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "eu", name: "Basque", native: "Euskara" },
  { code: "be", name: "Belarusian", native: "Беларуская" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "bs", name: "Bosnian", native: "Bosanski" },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "ca", name: "Catalan", native: "Català" },
  { code: "ceb", name: "Cebuano", native: "Cebuano" },
  { code: "zh-CN", name: "Chinese (Simplified)", native: "简体中文" },
  { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "en", name: "English", native: "English" },
  { code: "eo", name: "Esperanto", native: "Esperanto" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "fr", name: "French", native: "Français" },
  { code: "fy", name: "Frisian", native: "Frysk" },
  { code: "gl", name: "Galician", native: "Galego" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "ht", name: "Haitian Creole", native: "Kreyòl" },
  { code: "ha", name: "Hausa", native: "Hausa" },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "he", name: "Hebrew", native: "עברית" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "hmn", name: "Hmong", native: "Hmong" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "is", name: "Icelandic", native: "Íslenska" },
  { code: "ig", name: "Igbo", native: "Igbo" },
  { code: "id", name: "Indonesian", native: "Indonesia" },
  { code: "ga", name: "Irish", native: "Gaeilge" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "jv", name: "Javanese", native: "Basa Jawa" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "kk", name: "Kazakh", native: "Қазақ" },
  { code: "km", name: "Khmer", native: "ខ្មែរ" },
  { code: "rw", name: "Kinyarwanda", native: "Kinyarwanda" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "ku", name: "Kurdish", native: "Kurdî" },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "la", name: "Latin", native: "Latina" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "mk", name: "Macedonian", native: "Македонски" },
  { code: "mg", name: "Malagasy", native: "Malagasy" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "mt", name: "Maltese", native: "Malti" },
  { code: "mi", name: "Maori", native: "Te Reo Māori" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "my", name: "Myanmar", native: "မြန်မာ" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "ny", name: "Nyanja", native: "Chichewa" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "ps", name: "Pashto", native: "پښتو" },
  { code: "fa", name: "Persian", native: "فارسی" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "sm", name: "Samoan", native: "Gagana Samoa" },
  { code: "gd", name: "Scottish Gaelic", native: "Gàidhlig" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "st", name: "Sesotho", native: "Sesotho" },
  { code: "sn", name: "Shona", native: "ChiShona" },
  { code: "sd", name: "Sindhi", native: "سنڌي" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "sl", name: "Slovenian", native: "Slovenščina" },
  { code: "so", name: "Somali", native: "Soomaali" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "su", name: "Sundanese", native: "Basa Sunda" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "tl", name: "Tagalog", native: "Tagalog" },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "tt", name: "Tatar", native: "Татар" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "tk", name: "Turkmen", native: "Türkmen" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "ug", name: "Uyghur", native: "ئۇيغۇر" },
  { code: "uz", name: "Uzbek", native: "Oʻzbek" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "cy", name: "Welsh", native: "Cymraeg" },
  { code: "xh", name: "Xhosa", native: "isiXhosa" },
  { code: "yi", name: "Yiddish", native: "ייִדיש" },
  { code: "yo", name: "Yoruba", native: "Yorùbá" },
  { code: "zu", name: "Zulu", native: "isiZulu" },
];

const PHRASE_CATEGORIES = [
  {
    id: "greetings",
    name: "Greetings",
    icon: "👋",
    phrases: [
      { en: "Hello", key: "hello" },
      { en: "Good morning", key: "good_morning" },
      { en: "Good evening", key: "good_evening" },
      { en: "Good night", key: "good_night" },
      { en: "How are you?", key: "how_are_you" },
      { en: "Nice to meet you", key: "nice_to_meet" },
      { en: "Thank you", key: "thank_you" },
      { en: "You're welcome", key: "welcome" },
      { en: "Please", key: "please" },
      { en: "Excuse me", key: "excuse_me" },
      { en: "Sorry", key: "sorry" },
      { en: "Goodbye", key: "goodbye" },
    ],
  },
  {
    id: "travel",
    name: "Travel",
    icon: "✈",
    phrases: [
      { en: "Where is the airport?", key: "airport" },
      { en: "I need a taxi", key: "taxi" },
      { en: "How much does it cost?", key: "how_much" },
      { en: "Where is the hotel?", key: "hotel" },
      { en: "I have a reservation", key: "reservation" },
      { en: "What time does the train leave?", key: "train_time" },
      { en: "I am lost", key: "lost" },
      { en: "Can you help me?", key: "help_me" },
      { en: "I don't speak this language", key: "dont_speak" },
      { en: "Do you speak English?", key: "speak_english" },
    ],
  },
  {
    id: "food",
    name: "Food & dining",
    icon: "🍽",
    phrases: [
      { en: "A table for two, please", key: "table_two" },
      { en: "The menu, please", key: "menu" },
      { en: "I am vegetarian", key: "vegetarian" },
      { en: "I am allergic to nuts", key: "allergy" },
      { en: "The bill, please", key: "bill" },
      { en: "It was delicious", key: "delicious" },
      { en: "Water, please", key: "water" },
      { en: "I would like to order", key: "order" },
    ],
  },
  {
    id: "business",
    name: "Business",
    icon: "💼",
    phrases: [
      { en: "Nice to do business with you", key: "business" },
      { en: "Can we schedule a meeting?", key: "meeting" },
      { en: "I will send you an email", key: "email" },
      { en: "What is your phone number?", key: "phone" },
      { en: "I agree", key: "agree" },
      { en: "I disagree", key: "disagree" },
      { en: "Let me think about it", key: "think" },
      { en: "When is the deadline?", key: "deadline" },
    ],
  },
  {
    id: "emergency",
    name: "Emergency",
    icon: "🚨",
    phrases: [
      { en: "Help!", key: "help" },
      { en: "Call the police", key: "police" },
      { en: "I need a doctor", key: "doctor" },
      { en: "Call an ambulance", key: "ambulance" },
      { en: "Fire!", key: "fire" },
      { en: "I need medicine", key: "medicine" },
      { en: "Where is the hospital?", key: "hospital" },
      { en: "It is an emergency", key: "emergency" },
    ],
  },
  {
    id: "shopping",
    name: "Shopping",
    icon: "🛒",
    phrases: [
      { en: "How much is this?", key: "price" },
      { en: "Do you accept credit cards?", key: "credit" },
      { en: "Can I try this on?", key: "try_on" },
      { en: "I am just looking", key: "looking" },
      { en: "Do you have a discount?", key: "discount" },
      { en: "I would like a receipt", key: "receipt" },
      { en: "Where is the checkout?", key: "checkout" },
    ],
  },
  {
    id: "tech",
    name: "Tech & work",
    icon: "💻",
    phrases: [
      { en: "The internet is not working", key: "internet" },
      { en: "What is the Wi-Fi password?", key: "wifi" },
      { en: "Can you share your screen?", key: "screen" },
      { en: "I will be late to the meeting", key: "late" },
      { en: "Please send me the file", key: "file" },
      { en: "It works now", key: "works" },
      { en: "There is a bug", key: "bug" },
    ],
  },
  {
    id: "social",
    name: "Social",
    icon: "💬",
    phrases: [
      { en: "What is your name?", key: "your_name" },
      { en: "My name is...", key: "my_name" },
      { en: "Where are you from?", key: "from_where" },
      { en: "I love this place", key: "love_place" },
      { en: "See you later", key: "see_later" },
      { en: "Congratulations!", key: "congrats" },
      { en: "Happy birthday!", key: "birthday" },
    ],
  },
];

function getLanguage(code) {
  return LANGUAGES.find((l) => l.code === code) || LANGUAGES.find((l) => l.code === "en");
}

function targetLanguages() {
  return LANGUAGES.filter((l) => l.code !== "auto");
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { LANGUAGES, PHRASE_CATEGORIES, getLanguage, targetLanguages };
} else {
  window.TranslateLangs = { LANGUAGES, PHRASE_CATEGORIES, getLanguage, targetLanguages };
}
