(function (root) {
  root.FlagQuizAirportsData = {
    af: { iata: "KBL", city: "Kabul", cityHe: "קאבול", airport: "Hamid Karzai", airportHe: "חמיד כרזאי" },
    al: { iata: "TIA", city: "Tirana", cityHe: "טירנה", airport: "Tirana", airportHe: "טירנה" },
    dz: { iata: "ALG", city: "Algiers", cityHe: "אלג'יר", airport: "Houari Boumediene", airportHe: "חווארי בומדיין" },
    ad: { iata: "LEU", city: "La Seu d'Urgell", cityHe: "לה סאו", airport: "Andorra–La Seu", airportHe: "אנדורה" },
    ao: { iata: "LAD", city: "Luanda", cityHe: "לואנדה", airport: "Quatro de Fevereiro", airportHe: "לואנדה" },
    ar: { iata: "EZE", city: "Buenos Aires", cityHe: "בואנוס איירס", airport: "Ezeiza", airportHe: "אסייסה" },
    am: { iata: "EVN", city: "Yerevan", cityHe: "ירוואן", airport: "Zvartnots", airportHe: "זווארטנוץ" },
    au: { iata: "SYD", city: "Sydney", cityHe: "סידני", airport: "Kingsford Smith", airportHe: "קינגספורד סמית'" },
    at: { iata: "VIE", city: "Vienna", cityHe: "וינה", airport: "Vienna", airportHe: "וינה" },
    az: { iata: "GYD", city: "Baku", cityHe: "באקו", airport: "Heydar Aliyev", airportHe: "היידר אלייב" },
    bs: { iata: "NAS", city: "Nassau", cityHe: "נסאו", airport: "Lynden Pindling", airportHe: "נסאו" },
    bh: { iata: "BAH", city: "Manama", cityHe: "מנאמה", airport: "Bahrain", airportHe: "בחריין" },
    bd: { iata: "DAC", city: "Dhaka", cityHe: "דאקה", airport: "Hazrat Shahjalal", airportHe: "דאקה" },
    bb: { iata: "BGI", city: "Bridgetown", cityHe: "ברידג'טאון", airport: "Grantley Adams", airportHe: "גרנטלי אדמס" },
    by: { iata: "MSQ", city: "Minsk", cityHe: "מינסק", airport: "Minsk", airportHe: "מינסק" },
    be: { iata: "BRU", city: "Brussels", cityHe: "בריסל", airport: "Brussels", airportHe: "בריסל" },
    bz: { iata: "BZE", city: "Belize City", cityHe: "בליז סיטי", airport: "Philip S. W. Goldson", airportHe: "גולדסון" },
    bj: { iata: "COO", city: "Cotonou", cityHe: "קוטונו", airport: "Cadjehoun", airportHe: "קוטונו" },
    bt: { iata: "PBH", city: "Paro", cityHe: "פארו", airport: "Paro", airportHe: "פארו" },
    bo: { iata: "VVI", city: "Santa Cruz", cityHe: "סנטה קרוס", airport: "Viru Viru", airportHe: "וירו וירו" },
    ba: { iata: "SJJ", city: "Sarajevo", cityHe: "סרייבו", airport: "Sarajevo", airportHe: "סרייבו" },
    bw: { iata: "GBE", city: "Gaborone", cityHe: "גאבורונה", airport: "Sir Seretse Khama", airportHe: "גאבורונה" },
    br: { iata: "GRU", city: "São Paulo", cityHe: "סאו פאולו", airport: "Guarulhos", airportHe: "גואורולהוס" },
    bn: { iata: "BWN", city: "Bandar Seri Begawan", cityHe: "בנדר סרי בגוואן", airport: "Brunei", airportHe: "ברוניי" },
    bg: { iata: "SOF", city: "Sofia", cityHe: "סופיה", airport: "Sofia", airportHe: "סופיה" },
    bf: { iata: "OUA", city: "Ouagadougou", cityHe: "ואגאדוגו", airport: "Ouagadougou", airportHe: "ואגאדוגו" },
    bi: { iata: "BJM", city: "Bujumbura", cityHe: "בוג'ומבורה", airport: "Bujumbura", airportHe: "בוג'ומבורה" },
    kh: { iata: "PNH", city: "Phnom Penh", cityHe: "פנום פן", airport: "Phnom Penh", airportHe: "פנום פן" },
    cm: { iata: "DLA", city: "Douala", cityHe: "דואלה", airport: "Douala", airportHe: "דואלה" },
    ca: { iata: "YYZ", city: "Toronto", cityHe: "טורונטו", airport: "Pearson", airportHe: "פירסון" },
    cv: { iata: "SID", city: "Sal", cityHe: "סאל", airport: "Amílcar Cabral", airportHe: "אמילקר קברל" },
    cf: { iata: "BGF", city: "Bangui", cityHe: "בנגי", airport: "Bangui", airportHe: "בנגי" },
    td: { iata: "NDJ", city: "N'Djamena", cityHe: "נג'מנה", airport: "N'Djamena", airportHe: "נג'מנה" },
    cl: { iata: "SCL", city: "Santiago", cityHe: "סנטיאגו", airport: "Arturo Merino Benítez", airportHe: "סנטיאגו" },
    cn: { iata: "PEK", city: "Beijing", cityHe: "בייג'ינג", airport: "Capital", airportHe: "קפיטל" },
    co: { iata: "BOG", city: "Bogotá", cityHe: "בוגוטה", airport: "El Dorado", airportHe: "אל דוראדו" },
    km: { iata: "HAH", city: "Moroni", cityHe: "מורוני", airport: "Prince Said Ibrahim", airportHe: "מורוני" },
    cg: { iata: "BZV", city: "Brazzaville", cityHe: "ברזוויל", airport: "Maya-Maya", airportHe: "מאיה־מאיה" },
    cd: { iata: "FIH", city: "Kinshasa", cityHe: "קינשסה", airport: "N'djili", airportHe: "נג'ילי" },
    cr: { iata: "SJO", city: "San José", cityHe: "סן חוסה", airport: "Juan Santamaría", airportHe: "חואן סנטמריה" },
    ci: { iata: "ABJ", city: "Abidjan", cityHe: "אביג'אן", airport: "Félix-Houphouët-Boigny", airportHe: "אביג'אן" },
    hr: { iata: "ZAG", city: "Zagreb", cityHe: "זאגרב", airport: "Zagreb", airportHe: "זאגרב" },
    cu: { iata: "HAV", city: "Havana", cityHe: "הוואנה", airport: "José Martí", airportHe: "חוסה מרטי" },
    cy: { iata: "LCA", city: "Larnaca", cityHe: "לרנקה", airport: "Larnaca", airportHe: "לרנקה" },
    cz: { iata: "PRG", city: "Prague", cityHe: "פראג", airport: "Václav Havel", airportHe: "ואצלב האוול" },
    dk: { iata: "CPH", city: "Copenhagen", cityHe: "קופנהגן", airport: "Kastrup", airportHe: "קסטרופ" },
    dj: { iata: "JIB", city: "Djibouti", cityHe: "ג'יבוטי", airport: "Djibouti–Ambouli", airportHe: "ג'יבוטי" },
    do: { iata: "SDQ", city: "Santo Domingo", cityHe: "סנטו דומינגו", airport: "Las Américas", airportHe: "לאס אמריקאס" },
    ec: { iata: "UIO", city: "Quito", cityHe: "קיטו", airport: "Mariscal Sucre", airportHe: "מריסקל סוקרה" },
    eg: { iata: "CAI", city: "Cairo", cityHe: "קהיר", airport: "Cairo", airportHe: "קהיר" },
    sv: { iata: "SAL", city: "San Salvador", cityHe: "סן סלוודור", airport: "El Salvador", airportHe: "אל סלוודור" },
    gq: { iata: "SSG", city: "Malabo", cityHe: "מלבו", airport: "Malabo", airportHe: "מלבו" },
    er: { iata: "ASM", city: "Asmara", cityHe: "אסמרה", airport: "Asmara", airportHe: "אסמרה" },
    ee: { iata: "TLL", city: "Tallinn", cityHe: "טאלין", airport: "Lennart Meri", airportHe: "טאלין" },
    sz: { iata: "SHO", city: "Manzini", cityHe: "מנזיני", airport: "King Mswati III", airportHe: "סווזילנד" },
    et: { iata: "ADD", city: "Addis Ababa", cityHe: "אדיס אבבה", airport: "Bole", airportHe: "בולה" },
    fj: { iata: "NAN", city: "Nadi", cityHe: "נאדי", airport: "Nadi", airportHe: "נאדי" },
    fi: { iata: "HEL", city: "Helsinki", cityHe: "הלסינקי", airport: "Vantaa", airportHe: "ונטאה" },
    fr: { iata: "CDG", city: "Paris", cityHe: "פריז", airport: "Charles de Gaulle", airportHe: "שארל דה גול" },
    ga: { iata: "LBV", city: "Libreville", cityHe: "ליברוויל", airport: "Léon-Mba", airportHe: "ליברוויל" },
    gm: { iata: "BJL", city: "Banjul", cityHe: "בנג'ול", airport: "Banjul", airportHe: "בנג'ול" },
    ge: { iata: "TBS", city: "Tbilisi", cityHe: "טביליסי", airport: "Tbilisi", airportHe: "טביליסי" },
    de: { iata: "FRA", city: "Frankfurt", cityHe: "פרנקפורט", airport: "Frankfurt", airportHe: "פרנקפורט" },
    gh: { iata: "ACC", city: "Accra", cityHe: "אקרה", airport: "Kotoka", airportHe: "קוטוקה" },
    gr: { iata: "ATH", city: "Athens", cityHe: "אתונה", airport: "Eleftherios Venizelos", airportHe: "וניזלוס" },
    gt: { iata: "GUA", city: "Guatemala City", cityHe: "גואטמלה סיטי", airport: "La Aurora", airportHe: "לה אורורה" },
    gn: { iata: "CKY", city: "Conakry", cityHe: "קונאקרי", airport: "Conakry", airportHe: "קונאקרי" },
    gy: { iata: "GEO", city: "Georgetown", cityHe: "ג'ורג'טאון", airport: "Cheddi Jagan", airportHe: "צ'די ג'אגן" },
    ht: { iata: "PAP", city: "Port-au-Prince", cityHe: "פורט או פרנס", airport: "Toussaint Louverture", airportHe: "פורט או פרנס" },
    hn: { iata: "TGU", city: "Tegucigalpa", cityHe: "טגוסיגלפה", airport: "Toncontín", airportHe: "טונקנטין" },
    hu: { iata: "BUD", city: "Budapest", cityHe: "בודפשט", airport: "Ferenc Liszt", airportHe: "ליסט" },
    is: { iata: "KEF", city: "Reykjavík", cityHe: "רייקיאוויק", airport: "Keflavík", airportHe: "קפלאוויק" },
    in: { iata: "DEL", city: "Delhi", cityHe: "דלהי", airport: "Indira Gandhi", airportHe: "אינדירה גנדי" },
    id: { iata: "CGK", city: "Jakarta", cityHe: "ג'קרטה", airport: "Soekarno–Hatta", airportHe: "סוקרנו־האטה" },
    ir: { iata: "IKA", city: "Tehran", cityHe: "טהרן", airport: "Imam Khomeini", airportHe: "אימאם חומייני" },
    iq: { iata: "BGW", city: "Baghdad", cityHe: "בגדאד", airport: "Baghdad", airportHe: "בגדאד" },
    ie: { iata: "DUB", city: "Dublin", cityHe: "דבלין", airport: "Dublin", airportHe: "דבלין" },
    il: { iata: "TLV", city: "Tel Aviv", cityHe: "תל אביב", airport: "Ben Gurion", airportHe: "בן גוריון" },
    it: { iata: "FCO", city: "Rome", cityHe: "רומא", airport: "Fiumicino", airportHe: "פיומיצ'ינו" },
    jm: { iata: "KIN", city: "Kingston", cityHe: "קינגסטון", airport: "Norman Manley", airportHe: "נורמן מאנלי" },
    jp: { iata: "HND", city: "Tokyo", cityHe: "טוקיו", airport: "Haneda", airportHe: "הנדה" },
    jo: { iata: "AMM", city: "Amman", cityHe: "עמאן", airport: "Queen Alia", airportHe: "קווין עליה" },
    kz: { iata: "NQZ", city: "Astana", cityHe: "אסטנה", airport: "Nursultan Nazarbayev", airportHe: "אסטנה" },
    ke: { iata: "NBO", city: "Nairobi", cityHe: "ניירובי", airport: "Jomo Kenyatta", airportHe: "ג'ומו קניאטה" },
    kw: { iata: "KWI", city: "Kuwait City", cityHe: "כווית", airport: "Kuwait", airportHe: "כווית" },
    kg: { iata: "FRU", city: "Bishkek", cityHe: "בישקק", airport: "Manas", airportHe: "מאנאס" },
    la: { iata: "VTE", city: "Vientiane", cityHe: "ויינטיאן", airport: "Wattay", airportHe: "ווטאי" },
    lv: { iata: "RIX", city: "Riga", cityHe: "ריגה", airport: "Riga", airportHe: "ריגה" },
    lb: { iata: "BEY", city: "Beirut", cityHe: "ביירות", airport: "Rafic Hariri", airportHe: "רפיק אל־חרירי" },
    ls: { iata: "MSU", city: "Maseru", cityHe: "מסרו", airport: "Moshoeshoe I", airportHe: "מסרו" },
    lr: { iata: "ROB", city: "Monrovia", cityHe: "מונרוביה", airport: "Roberts", airportHe: "רוברטס" },
    ly: { iata: "MJI", city: "Tripoli", cityHe: "טריפולי", airport: "Mitiga", airportHe: "מיטיגה" },
    lt: { iata: "VNO", city: "Vilnius", cityHe: "וילנה", airport: "Vilnius", airportHe: "וילנה" },
    lu: { iata: "LUX", city: "Luxembourg", cityHe: "לוקסמבורג", airport: "Luxembourg", airportHe: "לוקסמבורג" },
    mg: { iata: "TNR", city: "Antananarivo", cityHe: "אנטננריבו", airport: "Ivato", airportHe: "איוואטו" },
    mw: { iata: "LLW", city: "Lilongwe", cityHe: "לילונגווה", airport: "Kamuzu", airportHe: "קאמוזו" },
    my: { iata: "KUL", city: "Kuala Lumpur", cityHe: "קואלה לומפור", airport: "Kuala Lumpur", airportHe: "קואלה לומפור" },
    mv: { iata: "MLE", city: "Malé", cityHe: "מאלה", airport: "Velana", airportHe: "ולאנה" },
    ml: { iata: "BKO", city: "Bamako", cityHe: "במקו", airport: "Modibo Keita", airportHe: "במקו" },
    mt: { iata: "MLA", city: "Valletta", cityHe: "ולטה", airport: "Malta", airportHe: "מלטה" },
    mr: { iata: "NKC", city: "Nouakchott", cityHe: "נואקשוט", airport: "Nouakchott–Oumtounsy", airportHe: "נואקשוט" },
    mu: { iata: "MRU", city: "Port Louis", cityHe: "פורט לואי", airport: "Sir Seewoosagur Ramgoolam", airportHe: "מאוריציוס" },
    mx: { iata: "MEX", city: "Mexico City", cityHe: "מקסיקו סיטי", airport: "Benito Juárez", airportHe: "בניטו חוארס" },
    md: { iata: "RMO", city: "Chișinău", cityHe: "קישינב", airport: "Chișinău", airportHe: "קישינב" },
    mc: { iata: "MCM", city: "Monaco", cityHe: "מונקו", airport: "Monaco Heliport", airportHe: "מונקו" },
    mn: { iata: "UBN", city: "Ulaanbaatar", cityHe: "אולן בטור", airport: "Chinggis Khaan", airportHe: "צ'ינגיס חאן" },
    me: { iata: "TGD", city: "Podgorica", cityHe: "פודגוריצה", airport: "Podgorica", airportHe: "פודגוריצה" },
    ma: { iata: "CMN", city: "Casablanca", cityHe: "קזבלנקה", airport: "Mohammed V", airportHe: "מוחמד החמישי" },
    mz: { iata: "MPM", city: "Maputo", cityHe: "מפוטו", airport: "Maputo", airportHe: "מפוטו" },
    mm: { iata: "RGN", city: "Yangon", cityHe: "יאנגון", airport: "Yangon", airportHe: "יאנגון" },
    na: { iata: "WDH", city: "Windhoek", cityHe: "וינדהוק", airport: "Hosea Kutako", airportHe: "וינדהוק" },
    np: { iata: "KTM", city: "Kathmandu", cityHe: "קטמנדו", airport: "Tribhuvan", airportHe: "טריבהובן" },
    nl: { iata: "AMS", city: "Amsterdam", cityHe: "אמסטרדם", airport: "Schiphol", airportHe: "סכיפהול" },
    nz: { iata: "AKL", city: "Auckland", cityHe: "אוקלנד", airport: "Auckland", airportHe: "אוקלנד" },
    ni: { iata: "MGA", city: "Managua", cityHe: "מנגואה", airport: "Augusto C. Sandino", airportHe: "מנגואה" },
    ne: { iata: "NIM", city: "Niamey", cityHe: "ניאמיי", airport: "Diori Hamani", airportHe: "ניאמיי" },
    ng: { iata: "LOS", city: "Lagos", cityHe: "לאגוס", airport: "Murtala Muhammed", airportHe: "מורטלה מוחמד" },
    mk: { iata: "SKP", city: "Skopje", cityHe: "סקופיה", airport: "Skopje", airportHe: "סקופיה" },
    no: { iata: "OSL", city: "Oslo", cityHe: "אוסלו", airport: "Gardermoen", airportHe: "גארדרמואן" },
    om: { iata: "MCT", city: "Muscat", cityHe: "מסקט", airport: "Muscat", airportHe: "מסקט" },
    pk: { iata: "ISB", city: "Islamabad", cityHe: "איסלמאבאד", airport: "Islamabad", airportHe: "איסלמאבאד" },
    pa: { iata: "PTY", city: "Panama City", cityHe: "פנמה סיטי", airport: "Tocumen", airportHe: "טוקומן" },
    pg: { iata: "POM", city: "Port Moresby", cityHe: "פורט מורסבי", airport: "Jacksons", airportHe: "ג'קסונס" },
    py: { iata: "ASU", city: "Asunción", cityHe: "אסונסיון", airport: "Silvio Pettirossi", airportHe: "אסונסיון" },
    pe: { iata: "LIM", city: "Lima", cityHe: "לימה", airport: "Jorge Chávez", airportHe: "חורחה צ'אבס" },
    ph: { iata: "MNL", city: "Manila", cityHe: "מנילה", airport: "Ninoy Aquino", airportHe: "נינוי אקינו" },
    pl: { iata: "WAW", city: "Warsaw", cityHe: "ורשה", airport: "Chopin", airportHe: "שופן" },
    pt: { iata: "LIS", city: "Lisbon", cityHe: "ליסבון", airport: "Humberto Delgado", airportHe: "ליסבון" },
    qa: { iata: "DOH", city: "Doha", cityHe: "דוחה", airport: "Hamad", airportHe: "חמד" },
    ro: { iata: "OTP", city: "Bucharest", cityHe: "בוקרשט", airport: "Henri Coandă", airportHe: "אנרי קואנדה" },
    ru: { iata: "SVO", city: "Moscow", cityHe: "מוסקבה", airport: "Sheremetyevo", airportHe: "שרמטייבו" },
    rw: { iata: "KGL", city: "Kigali", cityHe: "קיגאלי", airport: "Kigali", airportHe: "קיגאלי" },
    sa: { iata: "RUH", city: "Riyadh", cityHe: "ריאד", airport: "King Khalid", airportHe: "המלך ח'אלד" },
    sn: { iata: "DSS", city: "Dakar", cityHe: "דקאר", airport: "Blaise Diagne", airportHe: "בלייז דיאן" },
    rs: { iata: "BEG", city: "Belgrade", cityHe: "בלגרד", airport: "Nikola Tesla", airportHe: "ניקולה טסלה" },
    sc: { iata: "SEZ", city: "Mahé", cityHe: "מהה", airport: "Seychelles", airportHe: "סיישל" },
    sl: { iata: "FNA", city: "Freetown", cityHe: "פריטאון", airport: "Lungi", airportHe: "לונגי" },
    sg: { iata: "SIN", city: "Singapore", cityHe: "סינגפור", airport: "Changi", airportHe: "צ'אנגי" },
    sk: { iata: "BTS", city: "Bratislava", cityHe: "ברטיסלאבה", airport: "M. R. Štefánik", airportHe: "ברטיסלאבה" },
    si: { iata: "LJU", city: "Ljubljana", cityHe: "לובליאנה", airport: "Jože Pučnik", airportHe: "לובליאנה" },
    so: { iata: "MGQ", city: "Mogadishu", cityHe: "מוגדישו", airport: "Aden Adde", airportHe: "מוגדישו" },
    za: { iata: "JNB", city: "Johannesburg", cityHe: "יוהנסבורג", airport: "O. R. Tambo", airportHe: "אור תמבו" },
    ss: { iata: "JUB", city: "Juba", cityHe: "ג'ובה", airport: "Juba", airportHe: "ג'ובה" },
    es: { iata: "MAD", city: "Madrid", cityHe: "מדריד", airport: "Adolfo Suárez Madrid–Barajas", airportHe: "בראחס" },
    lk: { iata: "CMB", city: "Colombo", cityHe: "קולומבו", airport: "Bandaranaike", airportHe: "בנדרנאיקה" },
    sd: { iata: "KRT", city: "Khartoum", cityHe: "חרטום", airport: "Khartoum", airportHe: "חרטום" },
    sr: { iata: "PBM", city: "Paramaribo", cityHe: "פרמריבו", airport: "Johan Adolf Pengel", airportHe: "פרמריבו" },
    se: { iata: "ARN", city: "Stockholm", cityHe: "סטוקהולם", airport: "Arlanda", airportHe: "ארלנדה" },
    ch: { iata: "ZRH", city: "Zurich", cityHe: "ציריך", airport: "Zurich", airportHe: "ציריך" },
    sy: { iata: "DAM", city: "Damascus", cityHe: "דמשק", airport: "Damascus", airportHe: "דמשק" },
    tw: { iata: "TPE", city: "Taipei", cityHe: "טאיפיי", airport: "Taoyuan", airportHe: "טאויואן" },
    tj: { iata: "DYU", city: "Dushanbe", cityHe: "דושנבה", airport: "Dushanbe", airportHe: "דושנבה" },
    tz: { iata: "DAR", city: "Dar es Salaam", cityHe: "דאר א־סלאם", airport: "Julius Nyerere", airportHe: "נייררה" },
    th: { iata: "BKK", city: "Bangkok", cityHe: "בנגקוק", airport: "Suvarnabhumi", airportHe: "סובארנבהומי" },
    tl: { iata: "DIL", city: "Dili", cityHe: "דילי", airport: "Presidente Nicolau Lobato", airportHe: "דילי" },
    tg: { iata: "LFW", city: "Lomé", cityHe: "לומה", airport: "Gnassingbé Eyadéma", airportHe: "לומה" },
    to: { iata: "TBU", city: "Nukuʻalofa", cityHe: "נוקואלופה", airport: "Fuaʻamotu", airportHe: "פואמוטו" },
    tt: { iata: "POS", city: "Port of Spain", cityHe: "פורט אוף ספיין", airport: "Piarco", airportHe: "פיארקו" },
    tn: { iata: "TUN", city: "Tunis", cityHe: "תוניס", airport: "Carthage", airportHe: "קרתגו" },
    tr: { iata: "IST", city: "Istanbul", cityHe: "איסטנבול", airport: "Istanbul", airportHe: "איסטנבול" },
    tm: { iata: "ASB", city: "Ashgabat", cityHe: "אשגבאט", airport: "Ashgabat", airportHe: "אשגבאט" },
    ug: { iata: "EBB", city: "Entebbe", cityHe: "אנטבה", airport: "Entebbe", airportHe: "אנטבה" },
    ua: { iata: "KBP", city: "Kyiv", cityHe: "קייב", airport: "Boryspil", airportHe: "בוריספיל" },
    ae: { iata: "DXB", city: "Dubai", cityHe: "דובאי", airport: "Dubai", airportHe: "דובאי" },
    gb: { iata: "LHR", city: "London", cityHe: "לונדון", airport: "Heathrow", airportHe: "הית'רו" },
    us: { iata: "JFK", city: "New York", cityHe: "ניו יורק", airport: "John F. Kennedy", airportHe: "ג'ון פ. קנדי" },
    uy: { iata: "MVD", city: "Montevideo", cityHe: "מונטווידאו", airport: "Carrasco", airportHe: "קאראסקו" },
    uz: { iata: "TAS", city: "Tashkent", cityHe: "טשקנט", airport: "Tashkent", airportHe: "טשקנט" },
    vu: { iata: "VLI", city: "Port Vila", cityHe: "פורט וילה", airport: "Bauerfield", airportHe: "באוארפילד" },
    ve: { iata: "CCS", city: "Caracas", cityHe: "קראקס", airport: "Simón Bolívar", airportHe: "סימון בוליבר" },
    vn: { iata: "SGN", city: "Ho Chi Minh City", cityHe: "הו צ'י מין סיטי", airport: "Tan Son Nhat", airportHe: "טאן סון נהאט" },
    ye: { iata: "SAH", city: "Sana'a", cityHe: "צנעא", airport: "Sana'a", airportHe: "צנעא" },
    zm: { iata: "LUN", city: "Lusaka", cityHe: "לוסקה", airport: "Kenneth Kaunda", airportHe: "קנת קאונדה" },
    zw: { iata: "HRE", city: "Harare", cityHe: "הרארה", airport: "Robert Gabriel Mugabe", airportHe: "הרארה" },
    hk: { iata: "HKG", city: "Hong Kong", cityHe: "הונג קונג", airport: "Hong Kong", airportHe: "הונג קונג" },
    mo: { iata: "MFM", city: "Macau", cityHe: "מקאו", airport: "Macau", airportHe: "מקאו" },
    pr: { iata: "SJU", city: "San Juan", cityHe: "סן חואן", airport: "Luis Muñoz Marín", airportHe: "סן חואן" },
    xk: { iata: "PRN", city: "Pristina", cityHe: "פרישטינה", airport: "Pristina", airportHe: "פרישטינה" },
    ps: { iata: "GZA", city: "Gaza", cityHe: "עזה", airport: "Yasser Arafat", airportHe: "יאסר ערפאת" },
    tw: { iata: "TPE", city: "Taipei", cityHe: "טאיפיי", airport: "Taoyuan", airportHe: "טאויואן" },
    kr: { iata: "ICN", city: "Seoul", cityHe: "סיאול", airport: "Incheon", airportHe: "אינצ'ון" },
    kp: { iata: "FNJ", city: "Pyongyang", cityHe: "פיונגיאנג", airport: "Sunan", airportHe: "סונאן" },
    gl: { iata: "GOH", city: "Nuuk", cityHe: "נוק", airport: "Nuuk", airportHe: "נוק" },
    fo: { iata: "FAE", city: "Vágar", cityHe: "ואגאר", airport: "Vágar", airportHe: "ואגאר" },
    gi: { iata: "GIB", city: "Gibraltar", cityHe: "גיברלטר", airport: "Gibraltar", airportHe: "גיברלטר" },
    gu: { iata: "GUM", city: "Guam", cityHe: "גואם", airport: "Antonio B. Won Pat", airportHe: "גואם" },
    re: { iata: "RUN", city: "Saint-Denis", cityHe: "סן דני", airport: "Roland Garros", airportHe: "רולאן גארוס" },
    mq: { iata: "FDF", city: "Fort-de-France", cityHe: "פור-דה-פראנס", airport: "Martinique Aimé Césaire", airportHe: "מרטיניק" },
    gp: { iata: "PTP", city: "Pointe-à-Pitre", cityHe: "פואנט־א־פיטר", airport: "Pointe-à-Pitre", airportHe: "גוואדלופ" },
    pf: { iata: "PPT", city: "Papeete", cityHe: "פפאטה", airport: "Faa'a", airportHe: "פאאה" },
    nc: { iata: "NOU", city: "Nouméa", cityHe: "נומאה", airport: "La Tontouta", airportHe: "טונטוטה" },
    aw: { iata: "AUA", city: "Oranjestad", cityHe: "אורנייסטאד", airport: "Queen Beatrix", airportHe: "מלכת ביאטריקס" },
    cw: { iata: "CUR", city: "Willemstad", cityHe: "וילמסטאד", airport: "Hato", airportHe: "האטו" },
    ky: { iata: "GCM", city: "George Town", cityHe: "ג'ורג' טאון", airport: "Owen Roberts", airportHe: "קאימן" },
    bm: { iata: "BDA", city: "Hamilton", cityHe: "המילטון", airport: "L.F. Wade", airportHe: "ברמודה" },
    vi: { iata: "STT", city: "Charlotte Amalie", cityHe: "שארלוט אמאלי", airport: "Cyril E. King", airportHe: "סנט תומאס" },
    ag: { iata: "ANU", city: "St. John's", cityHe: "סנט ג'ון", airport: "V. C. Bird", airportHe: "אנטיגואה" },
    lc: { iata: "UVF", city: "Vieux Fort", cityHe: "ויו פור", airport: "Hewanorra", airportHe: "סנט לוסיה" },
    gd: { iata: "GND", city: "St. George's", cityHe: "סנט ג'ורג'", airport: "Maurice Bishop", airportHe: "גרנדה" },
    bb: { iata: "BGI", city: "Bridgetown", cityHe: "ברידג'טאון", airport: "Grantley Adams", airportHe: "גרנטלי אדמס" },
    mt: { iata: "MLA", city: "Luqa", cityHe: "לוקה", airport: "Malta", airportHe: "מלטה" },
    li: { iata: "ACH", city: "Altenrhein", cityHe: "אלטנריין", airport: "St. Gallen–Altenrhein", airportHe: "ליכטנשטיין" },
    sm: { iata: "RMI", city: "Rimini", cityHe: "רימיני", airport: "Federico Fellini", airportHe: "רימיני" },
    va: { iata: "FCO", city: "Rome", cityHe: "רומא", airport: "Fiumicino", airportHe: "פיומיצ'ינו" },
    ws: { iata: "APW", city: "Apia", cityHe: "אפיה", airport: "Faleolo", airportHe: "פאלאולו" },
    sb: { iata: "HIR", city: "Honiara", cityHe: "הוניארה", airport: "Honiara", airportHe: "הוניארה" },
    ki: { iata: "TRW", city: "Tarawa", cityHe: "טאראווה", airport: "Bonriki", airportHe: "בונריקי" },
    mh: { iata: "MAJ", city: "Majuro", cityHe: "מג'ורו", airport: "Amata Kabua", airportHe: "מג'ורו" },
    fm: { iata: "PNI", city: "Pohnpei", cityHe: "פונפיי", airport: "Pohnpei", airportHe: "פונפיי" },
    pw: { iata: "ROR", city: "Koror", cityHe: "קורור", airport: "Roman Tmetuchl", airportHe: "פלאו" },
    nr: { iata: "INU", city: "Yaren", cityHe: "ירן", airport: "Nauru", airportHe: "נאורו" },
    tv: { iata: "FUN", city: "Funafuti", cityHe: "פונאפוטי", airport: "Funafuti", airportHe: "פונאפוטי" },
    ck: { iata: "RAR", city: "Avarua", cityHe: "אוורואה", airport: "Rarotonga", airportHe: "רארוטונגה" },
    nu: { iata: "IUE", city: "Alofi", cityHe: "אלופי", airport: "Niue", airportHe: "ניואה" },
    wf: { iata: "WLS", city: "Mata-Utu", cityHe: "מאטה אוטו", airport: "Hihifo", airportHe: "ווליס" },
    tc: { iata: "PLS", city: "Providenciales", cityHe: "פרובידנסיאלס", airport: "Providenciales", airportHe: "טורקס וקייקוס" },
    vg: { iata: "EIS", city: "Road Town", cityHe: "רואד טאון", airport: "Terrance B. Lettsome", airportHe: "איי הבתולה" },
    ai: { iata: "AXA", city: "The Valley", cityHe: "דה ואלי", airport: "Clayton J. Lloyd", airportHe: "אנגווילה" },
    ms: { iata: "MNI", city: "Brades", cityHe: "בריידס", airport: "John A. Osborne", airportHe: "מונטסראט" },
    kn: { iata: "SKB", city: "Basseterre", cityHe: "בסטר", airport: "Robert L. Bradshaw", airportHe: "סנט קיטס" },
    vc: { iata: "SVD", city: "Kingstown", cityHe: "קינגסטאון", airport: "Argyle", airportHe: "סנט וינסנט" },
    dm: { iata: "DOM", city: "Roseau", cityHe: "רוזו", airport: "Douglas–Charles", airportHe: "דומיניקה" },
    st: { iata: "TMS", city: "São Tomé", cityHe: "סאו טומה", airport: "São Tomé", airportHe: "סאו טומה" },
    gw: { iata: "OXB", city: "Bissau", cityHe: "ביסאו", airport: "Osvaldo Vieira", airportHe: "ביסאו" },
    gq: { iata: "SSG", city: "Malabo", cityHe: "מלבו", airport: "Malabo", airportHe: "מלבו" },
  };
})(typeof window !== "undefined" ? window : globalThis);
