/** Auto-generated Wikipedia thumbnail URLs for national animals. Do not edit by hand — re-run _fetch-thumbs.mjs */
(function (root) {
  root.FlagQuizAnimalThumbs = {
  "African bush elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/178_Male_African_bush_elephant_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg/330px-178_Male_African_bush_elephant_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg",
  "African fish eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/African_fish_eagle%2C_Haliaeetus_vocifer%2C_at_Chobe_National_Park%2C_Botswana_%2833516612831%29.jpg/330px-African_fish_eagle%2C_Haliaeetus_vocifer%2C_at_Chobe_National_Park%2C_Botswana_%2833516612831%29.jpg",
  "African forest elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Loxodontacyclotis.jpg/330px-Loxodontacyclotis.jpg",
  "African leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Leopard_%28Panthera_pardus_pardus%29_Kruger.jpg/330px-Leopard_%28Panthera_pardus_pardus%29_Kruger.jpg",
  "Akhal-Teke": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Dagat-Geli.jpg/330px-Dagat-Geli.jpg",
  "Alpine ibex": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg/330px-003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg",
  "American flamingo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/American_Flamingo_JG.jpg/330px-American_Flamingo_JG.jpg",
  "Andean condor": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AndeanCondorMale.jpg/330px-AndeanCondorMale.jpg",
  "Arabian leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/PikiWiki_Israel_14861_judean_desert_leopard_cropped.JPG/330px-PikiWiki_Israel_14861_judean_desert_leopard_cropped.JPG",
  "Arabian oryx": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Arabian_oryx_%28oryx_leucoryx%29.jpg/330px-Arabian_oryx_%28oryx_leucoryx%29.jpg",
  "Argali": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ovis_ammon_%28cropped%29.jpg/330px-Ovis_ammon_%28cropped%29.jpg",
  "Armenian mouflon": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Armenian_mouflon.jpg/330px-Armenian_mouflon.jpg",
  "Asian elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Elephas_maximus_%28Bandipur%29.jpg/330px-Elephas_maximus_%28Bandipur%29.jpg",
  "Asiatic cheetah": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Delbar_%28Iranian_Cheetah%29_01_%28cropped%29.jpg",
  "Baird's tapir": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Baird%27s_tapir_mother_with_baby_%2892151%29.jpg/330px-Baird%27s_tapir_mother_with_baby_%2892151%29.jpg",
  "Bald eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg/330px-Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg",
  "Barbary macaque": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Macaca_sylvanus.Mother_and_baby.jpg/330px-Macaca_sylvanus.Mother_and_baby.jpg",
  "Barn swallow": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Rauchschwalbe_Hirundo_rustica.jpg/330px-Rauchschwalbe_Hirundo_rustica.jpg",
  "Bengal tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg/330px-Bengal_tiger_in_Sanjay_Dubri_Tiger_Reserve_December_2024_by_Tisha_Mukherjee_11.jpg",
  "Bermuda petrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bermuda_Petrel_From_The_Crossley_ID_Guide_Eastern_Birds%2C_crop.jpg/330px-Bermuda_Petrel_From_The_Crossley_ID_Guide_Eastern_Birds%2C_crop.jpg",
  "Black rhinoceros": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Black_Rhino_at_Working_with_Wildlife.jpg/330px-Black_Rhino_at_Working_with_Wildlife.jpg",
  "Blue rock thrush": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Monticola_solitarius%2C_Spain_1.jpg/330px-Monticola_solitarius%2C_Spain_1.jpg",
  "Brown bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/2010-kodiak-bear-1.jpg/330px-2010-kodiak-bear-1.jpg",
  "Brown pelican": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Brown_pelican_in_flight_%28Bodega_Bay%29.jpg/330px-Brown_pelican_in_flight_%28Bodega_Bay%29.jpg",
  "Chicken": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Male_and_female_chicken_sitting_together.jpg/330px-Male_and_female_chicken_sitting_together.jpg",
  "Common chimpanzee": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg/330px-015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
  "Common coquí": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Common_Coqu%C3%AD.jpg",
  "Common dolphin": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Common_dolphin_noaa.jpg/330px-Common_dolphin_noaa.jpg",
  "Common kestrel": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Common_kestrel_falco_tinnunculus.jpg/330px-Common_kestrel_falco_tinnunculus.jpg",
  "Common nightingale": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Luscinia_megarhynchos_-_Common_nightingale_-_Nachtegaal_%28cropped%29.jpg/330px-Luscinia_megarhynchos_-_Common_nightingale_-_Nachtegaal_%28cropped%29.jpg",
  "Cuban trogon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuban_trogon_%28Priotelus_temnurus%29.JPG/330px-Cuban_trogon_%28Priotelus_temnurus%29.JPG",
  "Dama gazelle": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Gazella_dama_ruficollis_3zz.jpg/330px-Gazella_dama_ruficollis_3zz.jpg",
  "Dodo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oxford_Dodo_display.jpg/330px-Oxford_Dodo_display.jpg",
  "Dromedary": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Camelus_dromedarius_in_Nuweiba.jpg/330px-Camelus_dromedarius_in_Nuweiba.jpg",
  "Dugong": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Dugong.JPG/330px-Dugong.JPG",
  "Eurasian lynx": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Lynx_Nationalpark_Bayerischer_Wald_01.jpg/330px-Lynx_Nationalpark_Bayerischer_Wald_01.jpg",
  "Eurasian oystercatcher": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Haematopus_ostralegus_He.jpg/330px-Haematopus_ostralegus_He.jpg",
  "European bison": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/European_bison_%28Bison_bonasus%29_male_Bia%C5%82owieza.jpg/330px-European_bison_%28Bison_bonasus%29_male_Bia%C5%82owieza.jpg",
  "European pine marten": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pine_Marten_%2848173751702%29.jpg/330px-Pine_Marten_%2848173751702%29.jpg",
  "European robin": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Erithacus_rubecula_with_cocked_head.jpg/330px-Erithacus_rubecula_with_cocked_head.jpg",
  "Fennec fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Fennec_Fox_Vulpes_zerda.jpg/330px-Fennec_Fox_Vulpes_zerda.jpg",
  "Formosan black bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Formosan_Black_Bear.JPG/330px-Formosan_Black_Bear.JPG",
  "Gemsbok": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gemsbok_%28Oryx_gazella%29_male.jpg/330px-Gemsbok_%28Oryx_gazella%29_male.jpg",
  "Giant panda": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/330px-Grosser_Panda.JPG",
  "Giraffe": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/330px-Giraffe_Mikumi_National_Park.jpg",
  "Golden eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/015_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_%28Switzerland%29_Photo_by_Giles_Laurent.jpg/330px-015_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_%28Switzerland%29_Photo_by_Giles_Laurent.jpg",
  "Gray wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/330px-Eurasian_wolf_2.jpg",
  "Great frigatebird": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Male_greater_frigate_bird_displaying.jpg/330px-Male_greater_frigate_bird_displaying.jpg",
  "Green pheasant": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Phasianus_versicolor_in_Japan.JPG/330px-Phasianus_versicolor_in_Japan.JPG",
  "Grenada dove": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ece310767-fig-0001-m.jpg/330px-Ece310767-fig-0001-m.jpg",
  "Grey crowned crane": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Grey_crowned_crane_%28Balearica_regulorum_gibbericeps%29.jpg/330px-Grey_crowned_crane_%28Balearica_regulorum_gibbericeps%29.jpg",
  "Guam kingfisher": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Micronesian_Kingfisher_1644.jpg/330px-Micronesian_Kingfisher_1644.jpg",
  "Gyrfalcon": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Falco_rusticolus_white_cropped.jpg/330px-Falco_rusticolus_white_cropped.jpg",
  "Harpy eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Harpia_harpyja_001_800.jpg/330px-Harpia_harpyja_001_800.jpg",
  "Hispaniolan trogon": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Hispaniolan_Trogon_%28Priotelus_roseigaster%29_%288082799519%29.jpg/330px-Hispaniolan_Trogon_%28Priotelus_roseigaster%29_%288082799519%29.jpg",
  "Hoopoe": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Upupa_epops_Madrid_01.jpg/330px-Upupa_epops_Madrid_01.jpg",
  "Humpback whale": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Humpback_Whale_underwater_shot.jpg/330px-Humpback_Whale_underwater_shot.jpg",
  "Imperial amazon": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Amazona_imperialis_-Roseau_-Dominica_-aviary-6a-3c.jpg/330px-Amazona_imperialis_-Roseau_-Dominica_-aviary-6a-3c.jpg",
  "Indo-Pacific humpback dolphin": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Pink_Dolphin.JPG/330px-Pink_Dolphin.JPG",
  "Indochinese tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Panthera_tigris_corbetti_01.jpg/330px-Panthera_tigris_corbetti_01.jpg",
  "Irish hare": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Irish_Mountain_Hare_imported_from_iNaturalist_photo_322047161_on_22_April_2024.jpg/330px-Irish_Mountain_Hare_imported_from_iNaturalist_photo_322047161_on_22_April_2024.jpg",
  "Italian wolf": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/C._l._italicus_in_MNP.jpg/330px-C._l._italicus_in_MNP.jpg",
  "Jaguar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Standing_jaguar.jpg/330px-Standing_jaguar.jpg",
  "Karabakh horse": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Qarabaq_ati.jpg/330px-Qarabaq_ati.jpg",
  "Kiwi (bird)": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/TeTuatahianui.jpg/330px-TeTuatahianui.jpg",
  "Komodo dragon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/202306_Varanus_komodoensis.jpg/330px-202306_Varanus_komodoensis.jpg",
  "Lion": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/330px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
  "Lipizzan": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Lipizzaner_Conversano_Traviata.jpg/330px-Lipizzaner_Conversano_Traviata.jpg",
  "Llama": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Llamas%2C_Vernagt-Stausee%2C_Italy.jpg/330px-Llamas%2C_Vernagt-Stausee%2C_Italy.jpg",
  "Malayan tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/MalayanTiger.jpg/330px-MalayanTiger.jpg",
  "Markhor": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Markhor_Schraubenziege_Capra_falconeri_Zoo_Augsburg-02.jpg/330px-Markhor_Schraubenziege_Capra_falconeri_Zoo_Augsburg-02.jpg",
  "Moose": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/330px-Alaska_moose.jpg",
  "Mouflon": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Cyprus_mouflon_%28Ovis_gmelini_ophion%29.jpg/330px-Cyprus_mouflon_%28Ovis_gmelini_ophion%29.jpg",
  "Mountain gorilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Susa_group%2C_mountain_gorilla.jpg/330px-Susa_group%2C_mountain_gorilla.jpg",
  "Mute swan": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/CygneVaires.jpg/330px-CygneVaires.jpg",
  "North American beaver": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/330px-American_Beaver.jpg",
  "Okapi": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg/330px-Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg",
  "Pacific flying fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Polynesian_flying_fox_%28Pteropus_tonganus%29_in_flight_Taveuni.jpg/330px-Polynesian_flying_fox_%28Pteropus_tonganus%29_in_flight_Taveuni.jpg",
  "Palestine sunbird": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Palestine_sunbird_%28Cinnyris_osea_osea%29_male.jpg/330px-Palestine_sunbird_%28Cinnyris_osea_osea%29_male.jpg",
  "Palmchat": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Cigua-palmera-ave-nacional-dominicana.jpg/330px-Cigua-palmera-ave-nacional-dominicana.jpg",
  "Pampas fox": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Na_estrada%3F.jpg/330px-Na_estrada%3F.jpg",
  "Plains zebra": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg/330px-Equus_quagga_burchellii_-_Etosha%2C_2014.jpg",
  "Polar bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/330px-Polar_Bear_-_Alaska_%28cropped%29.jpg",
  "Portuguese Water Dog": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/C%C3%A3o_de_agua_Portugu%C3%AAs_2.jpg/330px-C%C3%A3o_de_agua_Portugu%C3%AAs_2.jpg",
  "Proboscis monkey": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Proboscis_Monkey_in_Borneo.jpg/330px-Proboscis_Monkey_in_Borneo.jpg",
  "Przewalski's horse": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Przewalskis_horse_02.jpg/330px-Przewalskis_horse_02.jpg",
  "Raggiana bird-of-paradise": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Raggiana_Bird-of-paradise_0A2A5379.jpg/330px-Raggiana_Bird-of-paradise_0A2A5379.jpg",
  "Red kangaroo": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Red_kangaroo_-_melbourne_zoo.jpg/330px-Red_kangaroo_-_melbourne_zoo.jpg",
  "Red-billed streamertail": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Red-billed_streamertail%28_Trochilus_polytmus%29_adult_male_2.jpg/330px-Red-billed_streamertail%28_Trochilus_polytmus%29_adult_male_2.jpg",
  "Red-crested turaco": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/RedcrestedTuraco.jpg/330px-RedcrestedTuraco.jpg",
  "Resplendent quetzal": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Resplendent_quetzal_san_gerardo_de_dota_3.31.24_DSC_3989-topaz-denoiseraw.jpg/330px-Resplendent_quetzal_san_gerardo_de_dota_3.31.24_DSC_3989-topaz-denoiseraw.jpg",
  "Ring-tailed lemur": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg/330px-Ring-tailed_lemur_%28Lemur_catta%29.jpg",
  "Rufous hornero": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Rufous_hornero_%28Furnarius_rufus%29_Colonia.jpg/330px-Rufous_hornero_%28Furnarius_rufus%29_Colonia.jpg",
  "Rufous-bellied thrush": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Turdus-rufiventris.jpg/330px-Turdus-rufiventris.jpg",
  "Sable antelope": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sable_antelope_%28Hippotragus_niger%29_adult_male.jpg/330px-Sable_antelope_%28Hippotragus_niger%29_adult_male.jpg",
  "Saint Lucia amazon": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Amazona_versicolor_-St_Lucia-5a.jpg/330px-Amazona_versicolor_-St_Lucia-5a.jpg",
  "Saint Vincent amazon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Amazona_guildingii_-Botanical_Gardens_-Kingstown_-Saint_Vincent-8a-4c.jpg/330px-Amazona_guildingii_-Botanical_Gardens_-Kingstown_-Saint_Vincent-8a-4c.jpg",
  "Saker falcon": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Falco_cherrug_%28Marek_Szczepanek%29.jpg/330px-Falco_cherrug_%28Marek_Szczepanek%29.jpg",
  "Saltwater crocodile": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/SaltwaterCrocodile%28%27Maximo%27%29.jpg/330px-SaltwaterCrocodile%28%27Maximo%27%29.jpg",
  "Scarlet ibis": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Oceanografic_Scarlet_Ibis_02.jpg/330px-Oceanografic_Scarlet_Ibis_02.jpg",
  "Secretarybird": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Secretary_bird_Mara_for_WC.jpg/330px-Secretary_bird_Mara_for_WC.jpg",
  "Siberian tiger": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/P.t.altaica_Tomak_Male.jpg/330px-P.t.altaica_Tomak_Male.jpg",
  "Snow leopard": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.JPG/330px-Irbis4.JPG",
  "Soemmerring's gazelle": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Parc_national_de_Yangudi_Rassa-Gazelle_de_Soemmerring_%282%29.jpg/330px-Parc_national_de_Yangudi_Rassa-Gazelle_de_Soemmerring_%282%29.jpg",
  "South Andean deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Reserva_Cerro_Castillo.JPG/330px-Reserva_Cerro_Castillo.JPG",
  "Southern lapwing": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Southern_Lapwing_-_Indaiatuba%2C_SP%2C_BR.jpg/330px-Southern_Lapwing_-_Indaiatuba%2C_SP%2C_BR.jpg",
  "Spanish Fighting Bull": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/El_Pilar_Bull_by_Alexander_Fiske-Harrison%2C_Seville_Feria_09.jpg/330px-El_Pilar_Bull_by_Alexander_Fiske-Harrison%2C_Seville_Feria_09.jpg",
  "Springbok": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/174_Male_Springbok_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg/330px-174_Male_Springbok_in_Etosha_National_Park_Photo_by_Giles_Laurent.jpg",
  "Sri Lankan elephant": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Tuskers_of_Sri_Lanka.jpg/330px-Tuskers_of_Sri_Lanka.jpg",
  "Steppe eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Steppe_Eagle_Portrait.jpg/330px-Steppe_Eagle_Portrait.jpg",
  "Striped hyena": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Striped_hyena_in_Bhigwan_August_2025_by_Tisha_Mukherjee_07_%28cropped%29.jpg/330px-Striped_hyena_in_Bhigwan_August_2025_by_Tisha_Mukherjee_07_%28cropped%29.jpg",
  "Syrian brown bear": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ursus_arctos_syriacus.jpg/330px-Ursus_arctos_syriacus.jpg",
  "Takin": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Thimphu-Takin-Reservat-06-2015-gje.jpg/330px-Thimphu-Takin-Reservat-06-2015-gje.jpg",
  "Thomson's gazelle": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Gacela_de_Thomson_%28Eudorcas_thomsonii%29%2C_parque_nacional_de_Amboseli%2C_Kenia%2C_2024-05-23%2C_DD_11.jpg/330px-Gacela_de_Thomson_%28Eudorcas_thomsonii%29%2C_parque_nacional_de_Amboseli%2C_Kenia%2C_2024-05-23%2C_DD_11.jpg",
  "Tooth-billed pigeon": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Naturalis_Biodiversity_Center_-_ZMA.AVES.56900_-_Didunculus_strigirostris_Jardine%2C_1845_-_Columbidae_-_skin_specimen.jpeg/330px-Naturalis_Biodiversity_Center_-_ZMA.AVES.56900_-_Didunculus_strigirostris_Jardine%2C_1845_-_Columbidae_-_skin_specimen.jpeg",
  "Tornjak": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Bosniantornjak.jpg/330px-Bosniantornjak.jpg",
  "Turquoise-browed motmot": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Turquoise-browed_motmot_%28Eumomota_superciliosa_apiaster%29_Copan_2.jpg/330px-Turquoise-browed_motmot_%28Eumomota_superciliosa_apiaster%29_Copan_2.jpg",
  "Venezuelan troupial": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Curacao-Icterus-Icterus-2013.JPG/330px-Curacao-Icterus-Icterus-2013.JPG",
  "Vicuña": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Vicuna_%2889163948%29_%28cropped%29.jpg/330px-Vicuna_%2889163948%29_%28cropped%29.jpg",
  "Water buffalo": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Water_buffalo_at_Rinca.jpg/330px-Water_buffalo_at_Rinca.jpg",
  "Western lowland gorilla": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Western_lowland_silverback_resting_on_forest_floor.jpg/330px-Western_lowland_silverback_resting_on_forest_floor.jpg",
  "White stork": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/White_stork_%28Ciconia_ciconia%29_Bia%C5%82owieza.jpg/330px-White_stork_%28Ciconia_ciconia%29_Bia%C5%82owieza.jpg",
  "White wagtail": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/20180415_015_Winterswijk_Witte_kwikstaart_%2840785272624%29.jpg/330px-20180415_015_Winterswijk_Witte_kwikstaart_%2840785272624%29.jpg",
  "White-bellied sea eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/White-bellied_Sea-eagle_0A2A8670.jpg/330px-White-bellied_Sea-eagle_0A2A8670.jpg",
  "White-tailed deer": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/White-tailed_deer.jpg/330px-White-tailed_deer.jpg",
  "White-tailed eagle": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/NZ7_5265_%2852812350718%29.jpg/330px-NZ7_5265_%2852812350718%29.jpg",
  "Yellowfin tuna": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Thunnus_albacares.png",
  "Zebu": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/A_well-fed_bull_in_Kuno_WS_AJTJ_P1070807.jpg/330px-A_well-fed_bull_in_Kuno_WS_AJTJ_P1070807.jpg"
};
})(typeof window !== "undefined" ? window : globalThis);
